# -*- coding: utf-8 -*-
"""sentiment_Trasformer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1My68Pdfac5n4v2bAi9aSSH3PnTGWsyCs
"""

# Step 1: Import Required Libraries

import pandas as pd
import numpy as np
import os
import random

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

print("Libraries imported successfully!")

# Step 2: Upload Sentiment Dataset

from google.colab import files

uploaded = files.upload()

print("File uploaded successfully!")

# Load the uploaded CSV file

import io

file_name = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("Dataset loaded successfully!")
print("File:", file_name)
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

# Step 3: Check Dataset Information

print("===== DATASET INFORMATION =====")

print("\nShape:")
print(df.shape)

print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDuplicate Rows:")
print(df.duplicated().sum())

print("\nSentiment Distribution:")
print(df["sentiment"].value_counts())

print("\nDomain Distribution:")
print(df["domain"].value_counts())

# Step 4: Encode Sentiment Labels

label_mapping = {
    "Negative": 0,
    "Neutral": 1,
    "Positive": 2
}

df["label"] = df["sentiment"].map(label_mapping)

print("Label mapping:", label_mapping)

print("\nFirst 10 encoded labels:")
display(df[["sentiment", "label"]].head(10))

print("\nEncoded label distribution:")
print(df["label"].value_counts().sort_index())

# Step 5: Create Train, Validation, and Test Splits

# First split: 80% temporary, 20% test
train_val_df, test_df = train_test_split(
    df,
    test_size=0.20,
    random_state=42,
    stratify=df["label"]
)

# Second split: 90% train, 10% validation of the remaining 80%
train_df, val_df = train_test_split(
    train_val_df,
    test_size=0.10,
    random_state=42,
    stratify=train_val_df["label"]
)

print("Dataset split completed successfully!")

print("\nTraining samples:", len(train_df))
print("Validation samples:", len(val_df))
print("Testing samples:", len(test_df))

print("\nTraining distribution:")
print(train_df["label"].value_counts().sort_index())

print("\nValidation distribution:")
print(val_df["label"].value_counts().sort_index())

print("\nTesting distribution:")
print(test_df["label"].value_counts().sort_index())

# Step 6: Convert Pandas DataFrames to Hugging Face Datasets

!pip -q install datasets

from datasets import Dataset

train_dataset = Dataset.from_pandas(
    train_df[["text", "label"]],
    preserve_index=False
)

val_dataset = Dataset.from_pandas(
    val_df[["text", "label"]],
    preserve_index=False
)

test_dataset = Dataset.from_pandas(
    test_df[["text", "label"]],
    preserve_index=False
)

print("Hugging Face datasets created successfully!")

print("\nTrain dataset:")
print(train_dataset)

print("\nValidation dataset:")
print(val_dataset)

print("\nTest dataset:")
print(test_dataset)

# Step 7: Create Common Evaluation Metrics

from sklearn.metrics import accuracy_score, precision_recall_fscore_support

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # Get predicted class
    predictions = np.argmax(predictions, axis=1)

    # Calculate metrics
    accuracy = accuracy_score(labels, predictions)

    precision, recall, f1, _ = precision_recall_fscore_support(
        labels,
        predictions,
        average="weighted",
        zero_division=0
    )

    return {
        "accuracy": accuracy,
        "precision": precision,
        "recall": recall,
        "f1": f1
    }

print("Evaluation metrics function created successfully!")

# Step 8: Load BERT Tokenizer and Model

from transformers import AutoTokenizer, AutoModelForSequenceClassification

BERT_MODEL_NAME = "bert-base-uncased"
NUM_LABELS = len(label_mapping)

bert_tokenizer = AutoTokenizer.from_pretrained(BERT_MODEL_NAME)

bert_model = AutoModelForSequenceClassification.from_pretrained(
    BERT_MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    },
    label2id=label_mapping
)

print("BERT loaded successfully!")
print("Model:", BERT_MODEL_NAME)
print("Number of labels:", NUM_LABELS)

# Step 9: Tokenize BERT datasets

def bert_tokenize_function(examples):
    return bert_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

bert_train_tokenized = train_dataset.map(
    bert_tokenize_function,
    batched=True
)

bert_val_tokenized = val_dataset.map(
    bert_tokenize_function,
    batched=True
)

bert_test_tokenized = test_dataset.map(
    bert_tokenize_function,
    batched=True
)

print("BERT tokenization completed!")

print("\nTrain features:")
print(bert_train_tokenized.features)

print("\nValidation features:")
print(bert_val_tokenized.features)

print("\nTest features:")
print(bert_test_tokenized.features)

# Step 10: Prepare BERT Datasets for Training

bert_train_tokenized = bert_train_tokenized.remove_columns(["text"])
bert_val_tokenized = bert_val_tokenized.remove_columns(["text"])
bert_test_tokenized = bert_test_tokenized.remove_columns(["text"])

bert_train_tokenized.set_format("torch")
bert_val_tokenized.set_format("torch")
bert_test_tokenized.set_format("torch")

print("BERT datasets prepared successfully!")

print("\nTrain columns:", bert_train_tokenized.column_names)
print("Validation columns:", bert_val_tokenized.column_names)
print("Test columns:", bert_test_tokenized.column_names)

# Step 11: BERT Training Configuration

from transformers import TrainingArguments

bert_training_args = TrainingArguments(
    output_dir="./bert_training_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

print("BERT training configuration created successfully!")
print("Epochs:", bert_training_args.num_train_epochs)
print("Train batch size:", bert_training_args.per_device_train_batch_size)
print("Learning rate:", bert_training_args.learning_rate)

# Step 13A: Disable torchvision to avoid the VideoReader compatibility issue

import sys

# Remove torchvision from the current Python session
if "torchvision" in sys.modules:
    del sys.modules["torchvision"]

# Tell Hugging Face Transformers that torchvision is unavailable
import os
os.environ["TRANSFORMERS_NO_TORCHVISION"] = "1"

print("Torchvision disabled for this training session!")

import torch

print("PyTorch:", torch.__version__)
print("CUDA:", torch.version.cuda)
print("GPU available:", torch.cuda.is_available())

if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# Step 13B: Train BERT

print("Starting BERT training...\n")

bert_train_result = bert_trainer.train()

print("\nBERT training completed successfully!")

# Step 14: Evaluate BERT on Test Dataset

print("Evaluating BERT on test dataset...\n")

bert_test_results = bert_trainer.evaluate(
    bert_test_tokenized
)

print("===== BERT Test Results =====")

for key, value in bert_test_results.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.4f}")

# Step 15: BERT Classification Report and Confusion Matrix

from sklearn.metrics import classification_report, confusion_matrix

print("Generating BERT predictions...\n")

bert_predictions = bert_trainer.predict(
    bert_test_tokenized
)

bert_y_pred = np.argmax(
    bert_predictions.predictions,
    axis=1
)

bert_y_true = bert_predictions.label_ids

target_names = [
    "Negative",
    "Neutral",
    "Positive"
]

print("===== BERT Classification Report =====")

print(
    classification_report(
        bert_y_true,
        bert_y_pred,
        target_names=target_names,
        digits=4
    )
)

print("===== BERT Confusion Matrix =====")

bert_cm = confusion_matrix(
    bert_y_true,
    bert_y_pred
)

print(bert_cm)

# Step 16: Save BERT Model

BERT_SAVE_PATH = "./bert_sentiment_model"

bert_trainer.save_model(BERT_SAVE_PATH)
bert_tokenizer.save_pretrained(BERT_SAVE_PATH)

print("BERT model saved successfully!")
print("Location:", BERT_SAVE_PATH)

# Step 16: Create Transformer Results Table and Save BERT

# Save BERT model
BERT_SAVE_PATH = "./bert_sentiment_model"

bert_trainer.save_model(BERT_SAVE_PATH)
bert_tokenizer.save_pretrained(BERT_SAVE_PATH)

print("BERT model saved successfully!")
print("Location:", BERT_SAVE_PATH)


# Create Transformer results table
transformer_results = pd.DataFrame([{
    "Model": "BERT",
    "Accuracy": bert_test_results["eval_accuracy"],
    "Precision": bert_test_results["eval_precision"],
    "Recall": bert_test_results["eval_recall"],
    "F1-Score": bert_test_results["eval_f1"]
}])

print("\n===== Transformer Results =====")
display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

# Step 17: Load mBERT Tokenizer and Model

MBERT_MODEL_NAME = "bert-base-multilingual-cased"

mbert_tokenizer = AutoTokenizer.from_pretrained(
    MBERT_MODEL_NAME
)

mbert_model = AutoModelForSequenceClassification.from_pretrained(
    MBERT_MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    },
    label2id=label_mapping
)

print("mBERT loaded successfully!")
print("Model:", MBERT_MODEL_NAME)
print("Number of labels:", NUM_LABELS)

# Step 18: Tokenize mBERT Datasets

def mbert_tokenize_function(examples):
    return mbert_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

mbert_train_tokenized = train_dataset.map(
    mbert_tokenize_function,
    batched=True
)

mbert_val_tokenized = val_dataset.map(
    mbert_tokenize_function,
    batched=True
)

mbert_test_tokenized = test_dataset.map(
    mbert_tokenize_function,
    batched=True
)

print("mBERT tokenization completed!")

print("\nTrain features:")
print(mbert_train_tokenized.features)

print("\nValidation features:")
print(mbert_val_tokenized.features)

print("\nTest features:")
print(mbert_test_tokenized.features)

# Step 19: Prepare mBERT Datasets for Training

mbert_train_tokenized = mbert_train_tokenized.remove_columns(["text"])
mbert_val_tokenized = mbert_val_tokenized.remove_columns(["text"])
mbert_test_tokenized = mbert_test_tokenized.remove_columns(["text"])

mbert_train_tokenized.set_format("torch")
mbert_val_tokenized.set_format("torch")
mbert_test_tokenized.set_format("torch")

print("mBERT datasets prepared successfully!")

print("\nTrain columns:", mbert_train_tokenized.column_names)
print("Validation columns:", mbert_val_tokenized.column_names)
print("Test columns:", mbert_test_tokenized.column_names)

# Step 20: mBERT Training Configuration

mbert_training_args = TrainingArguments(
    output_dir="./mbert_training_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

print("mBERT training configuration created successfully!")
print("Epochs:", mbert_training_args.num_train_epochs)
print("Train batch size:", mbert_training_args.per_device_train_batch_size)
print("Learning rate:", mbert_training_args.learning_rate)

# Step 21: Create mBERT Trainer

mbert_trainer = Trainer(
    model=mbert_model,
    args=mbert_training_args,
    train_dataset=mbert_train_tokenized,
    eval_dataset=mbert_val_tokenized,
    processing_class=mbert_tokenizer,
    compute_metrics=compute_metrics
)

print("mBERT Trainer created successfully!")

# Step 22: Train mBERT

print("Starting mBERT training...\n")

mbert_train_result = mbert_trainer.train()

print("\nmBERT training completed successfully!")

# Step 23: Evaluate mBERT on Test Dataset

print("Evaluating mBERT on test dataset...\n")

mbert_test_results = mbert_trainer.evaluate(
    mbert_test_tokenized
)

print("===== mBERT Test Results =====")

for key, value in mbert_test_results.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.4f}")

# Step 24: mBERT Classification Report and Confusion Matrix

print("Generating mBERT predictions...\n")

mbert_predictions = mbert_trainer.predict(
    mbert_test_tokenized
)

mbert_y_pred = np.argmax(
    mbert_predictions.predictions,
    axis=1
)

mbert_y_true = mbert_predictions.label_ids

target_names = [
    "Negative",
    "Neutral",
    "Positive"
]

print("===== mBERT Classification Report =====")

print(
    classification_report(
        mbert_y_true,
        mbert_y_pred,
        target_names=target_names,
        digits=4
    )
)

print("===== mBERT Confusion Matrix =====")

mbert_cm = confusion_matrix(
    mbert_y_true,
    mbert_y_pred
)
print(mbert_cm)

# Step 25: Save mBERT and Append Results

MBERT_SAVE_PATH = "./mbert_sentiment_model"

# Save model and tokenizer
mbert_trainer.save_model(MBERT_SAVE_PATH)
mbert_tokenizer.save_pretrained(MBERT_SAVE_PATH)

print("mBERT model saved successfully!")
print("Location:", MBERT_SAVE_PATH)


# Append mBERT results to the existing Transformer table
mbert_result_row = pd.DataFrame([{
    "Model": "mBERT",
    "Accuracy": mbert_test_results["eval_accuracy"],
    "Precision": mbert_test_results["eval_precision"],
    "Recall": mbert_test_results["eval_recall"],
    "F1-Score": mbert_test_results["eval_f1"]
}])

transformer_results = pd.concat(
    [transformer_results, mbert_result_row],
    ignore_index=True
)

print("\n===== Transformer Results =====")

display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

# Step 26: Load RoBERTa Tokenizer and Model

ROBERTA_MODEL_NAME = "roberta-base"

roberta_tokenizer = AutoTokenizer.from_pretrained(
    ROBERTA_MODEL_NAME
)

roberta_model = AutoModelForSequenceClassification.from_pretrained(
    ROBERTA_MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    },
    label2id=label_mapping
)

print("RoBERTa loaded successfully!")
print("Model:", ROBERTA_MODEL_NAME)
print("Number of labels:", NUM_LABELS)

# Step 27: Tokenize RoBERTa Datasets

def roberta_tokenize_function(examples):
    return roberta_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

roberta_train_tokenized = train_dataset.map(
    roberta_tokenize_function,
    batched=True
)

roberta_val_tokenized = val_dataset.map(
    roberta_tokenize_function,
    batched=True
)

roberta_test_tokenized = test_dataset.map(
    roberta_tokenize_function,
    batched=True
)

print("RoBERTa tokenization completed!")

print("\nTrain features:")
print(roberta_train_tokenized.features)

print("\nValidation features:")
print(roberta_val_tokenized.features)

print("\nTest features:")
print(roberta_test_tokenized.features)

# Step 28: Prepare RoBERTa Datasets for Training

roberta_train_tokenized = roberta_train_tokenized.remove_columns(["text"])
roberta_val_tokenized = roberta_val_tokenized.remove_columns(["text"])
roberta_test_tokenized = roberta_test_tokenized.remove_columns(["text"])

roberta_train_tokenized.set_format("torch")
roberta_val_tokenized.set_format("torch")
roberta_test_tokenized.set_format("torch")

print("RoBERTa datasets prepared successfully!")

print("\nTrain columns:", roberta_train_tokenized.column_names)
print("Validation columns:", roberta_val_tokenized.column_names)
print("Test columns:", roberta_test_tokenized.column_names)

# Step 29: RoBERTa Training Configuration

roberta_training_args = TrainingArguments(
    output_dir="./roberta_training_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

print("RoBERTa training configuration created successfully!")
print("Epochs:", roberta_training_args.num_train_epochs)
print("Train batch size:", roberta_training_args.per_device_train_batch_size)
print("Learning rate:", roberta_training_args.learning_rate)

# Step 30: Create RoBERTa Trainer

roberta_trainer = Trainer(
    model=roberta_model,
    args=roberta_training_args,
    train_dataset=roberta_train_tokenized,
    eval_dataset=roberta_val_tokenized,
    processing_class=roberta_tokenizer,
    compute_metrics=compute_metrics
)

print("RoBERTa Trainer created successfully!")

# Step 31: Train RoBERTa

print("Starting RoBERTa training...\n")

roberta_train_result = roberta_trainer.train()

print("\nRoBERTa training completed successfully!")

# Step 32: Evaluate RoBERTa on Test Dataset

print("Evaluating RoBERTa on test dataset...\n")

roberta_test_results = roberta_trainer.evaluate(
    roberta_test_tokenized
)

print("===== RoBERTa Test Results =====")

for key, value in roberta_test_results.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.4f}")

# Step 33: RoBERTa Classification Report and Confusion Matrix

print("Generating RoBERTa predictions...\n")

roberta_predictions = roberta_trainer.predict(
    roberta_test_tokenized
)

roberta_y_pred = np.argmax(
    roberta_predictions.predictions,
    axis=1
)

roberta_y_true = roberta_predictions.label_ids

target_names = [
    "Negative",
    "Neutral",
    "Positive"
]

print("===== RoBERTa Classification Report =====")

print(
    classification_report(
        roberta_y_true,
        roberta_y_pred,
        target_names=target_names,
        digits=4
    )
)

print("===== RoBERTa Confusion Matrix =====")

roberta_cm = confusion_matrix(
    roberta_y_true,
    roberta_y_pred
)

print(roberta_cm)

# Step 34: Save RoBERTa and Append Results

ROBERTA_SAVE_PATH = "./roberta_sentiment_model"

# Save model and tokenizer
roberta_trainer.save_model(ROBERTA_SAVE_PATH)
roberta_tokenizer.save_pretrained(ROBERTA_SAVE_PATH)

print("RoBERTa model saved successfully!")
print("Location:", ROBERTA_SAVE_PATH)


# Append RoBERTa test results to the existing table
roberta_result_row = pd.DataFrame([{
    "Model": "RoBERTa",
    "Accuracy": roberta_test_results["eval_accuracy"],
    "Precision": roberta_test_results["eval_precision"],
    "Recall": roberta_test_results["eval_recall"],
    "F1-Score": roberta_test_results["eval_f1"]
}])

transformer_results = pd.concat(
    [transformer_results, roberta_result_row],
    ignore_index=True
)

print("\n===== Transformer Results =====")

display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

# Step 35: Load XLM-RoBERTa Tokenizer and Model

XLMR_MODEL_NAME = "FacebookAI/xlm-roberta-base"

xlmr_tokenizer = AutoTokenizer.from_pretrained(
    XLMR_MODEL_NAME
)

xlmr_model = AutoModelForSequenceClassification.from_pretrained(
    XLMR_MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    },
    label2id=label_mapping
)

print("XLM-RoBERTa loaded successfully!")
print("Model:", XLMR_MODEL_NAME)
print("Number of labels:", NUM_LABELS)

# Step 36: Tokenize XLM-RoBERTa Datasets

def xlmr_tokenize_function(examples):
    return xlmr_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

xlmr_train_tokenized = train_dataset.map(
    xlmr_tokenize_function,
    batched=True
)

xlmr_val_tokenized = val_dataset.map(
    xlmr_tokenize_function,
    batched=True
)

xlmr_test_tokenized = test_dataset.map(
    xlmr_tokenize_function,
    batched=True
)

print("XLM-RoBERTa tokenization completed!")

print("\nTrain features:")
print(xlmr_train_tokenized.features)

print("\nValidation features:")
print(xlmr_val_tokenized.features)

print("\nTest features:")
print(xlmr_test_tokenized.features)

# Step 37: Prepare XLM-RoBERTa Datasets for Training

xlmr_train_tokenized = xlmr_train_tokenized.remove_columns(["text"])
xlmr_val_tokenized = xlmr_val_tokenized.remove_columns(["text"])
xlmr_test_tokenized = xlmr_test_tokenized.remove_columns(["text"])

xlmr_train_tokenized.set_format("torch")
xlmr_val_tokenized.set_format("torch")
xlmr_test_tokenized.set_format("torch")

print("XLM-RoBERTa datasets prepared successfully!")

print("\nTrain columns:", xlmr_train_tokenized.column_names)
print("Validation columns:", xlmr_val_tokenized.column_names)
print("Test columns:", xlmr_test_tokenized.column_names)

# Step 38: XLM-RoBERTa Training Configuration

xlmr_training_args = TrainingArguments(
    output_dir="./xlmr_training_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

print("XLM-RoBERTa training configuration created successfully!")
print("Epochs:", xlmr_training_args.num_train_epochs)
print("Train batch size:", xlmr_training_args.per_device_train_batch_size)
print("Learning rate:", xlmr_training_args.learning_rate)

# Step 39: Create XLM-RoBERTa Trainer

xlmr_trainer = Trainer(
    model=xlmr_model,
    args=xlmr_training_args,
    train_dataset=xlmr_train_tokenized,
    eval_dataset=xlmr_val_tokenized,
    processing_class=xlmr_tokenizer,
    compute_metrics=compute_metrics
)

print("XLM-RoBERTa Trainer created successfully!")

# Step 40: Train XLM-RoBERTa

print("Starting XLM-RoBERTa training...\n")

xlmr_train_result = xlmr_trainer.train()

print("\nXLM-RoBERTa training completed successfully!")

# Step 41: Evaluate XLM-RoBERTa on Test Dataset

print("Evaluating XLM-RoBERTa on test dataset...\n")

xlmr_test_results = xlmr_trainer.evaluate(
    xlmr_test_tokenized
)

print("===== XLM-RoBERTa Test Results =====")

for key, value in xlmr_test_results.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.4f}")

# Step 42: XLM-RoBERTa Classification Report and Confusion Matrix

print("Generating XLM-RoBERTa predictions...\n")

xlmr_predictions = xlmr_trainer.predict(
    xlmr_test_tokenized
)

xlmr_y_pred = np.argmax(
    xlmr_predictions.predictions,
    axis=1
)

xlmr_y_true = xlmr_predictions.label_ids

target_names = [
    "Negative",
    "Neutral",
    "Positive"
]

print("===== XLM-RoBERTa Classification Report =====")

print(
    classification_report(
        xlmr_y_true,
        xlmr_y_pred,
        target_names=target_names,
        digits=4
    )
)

print("===== XLM-RoBERTa Confusion Matrix =====")

xlmr_cm = confusion_matrix(
    xlmr_y_true,
    xlmr_y_pred
)

print(xlmr_cm)

# Step 43: Save XLM-RoBERTa and Append Results

XLMR_SAVE_PATH = "./xlmr_sentiment_model"

# Save model and tokenizer
xlmr_trainer.save_model(XLMR_SAVE_PATH)
xlmr_tokenizer.save_pretrained(XLMR_SAVE_PATH)

print("XLM-RoBERTa model saved successfully!")
print("Location:", XLMR_SAVE_PATH)


# Append XLM-RoBERTa test results to the existing table
xlmr_result_row = pd.DataFrame([{
    "Model": "XLM-RoBERTa",
    "Accuracy": xlmr_test_results["eval_accuracy"],
    "Precision": xlmr_test_results["eval_precision"],
    "Recall": xlmr_test_results["eval_recall"],
    "F1-Score": xlmr_test_results["eval_f1"]
}])

transformer_results = pd.concat(
    [transformer_results, xlmr_result_row],
    ignore_index=True
)

print("\n===== Transformer Results =====")

display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

# Step 44: Load MuRIL Tokenizer and Model

MURIL_MODEL_NAME = "google/muril-base-cased"

muril_tokenizer = AutoTokenizer.from_pretrained(
    MURIL_MODEL_NAME
)

muril_model = AutoModelForSequenceClassification.from_pretrained(
    MURIL_MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    },
    label2id=label_mapping
)

print("MuRIL loaded successfully!")
print("Model:", MURIL_MODEL_NAME)
print("Number of labels:", NUM_LABELS)

# Step 45: Tokenize MuRIL Datasets

def muril_tokenize_function(examples):
    return muril_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

muril_train_tokenized = train_dataset.map(
    muril_tokenize_function,
    batched=True
)

muril_val_tokenized = val_dataset.map(
    muril_tokenize_function,
    batched=True
)

muril_test_tokenized = test_dataset.map(
    muril_tokenize_function,
    batched=True
)

print("MuRIL tokenization completed!")

print("\nTrain features:")
print(muril_train_tokenized.features)

print("\nValidation features:")
print(muril_val_tokenized.features)

print("\nTest features:")
print(muril_test_tokenized.features)

# Step 46: Prepare MuRIL Datasets for Training

muril_train_tokenized = muril_train_tokenized.remove_columns(["text"])
muril_val_tokenized = muril_val_tokenized.remove_columns(["text"])
muril_test_tokenized = muril_test_tokenized.remove_columns(["text"])

muril_train_tokenized.set_format("torch")
muril_val_tokenized.set_format("torch")
muril_test_tokenized.set_format("torch")

print("MuRIL datasets prepared successfully!")

print("\nTrain columns:", muril_train_tokenized.column_names)
print("Validation columns:", muril_val_tokenized.column_names)
print("Test columns:", muril_test_tokenized.column_names)

# Step 47: MuRIL Training Configuration

muril_training_args = TrainingArguments(
    output_dir="./muril_training_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

print("MuRIL training configuration created successfully!")
print("Epochs:", muril_training_args.num_train_epochs)
print("Train batch size:", muril_training_args.per_device_train_batch_size)
print("Learning rate:", muril_training_args.learning_rate)

# Step 48: Create MuRIL Trainer

muril_trainer = Trainer(
    model=muril_model,
    args=muril_training_args,
    train_dataset=muril_train_tokenized,
    eval_dataset=muril_val_tokenized,
    processing_class=muril_tokenizer,
    compute_metrics=compute_metrics
)

print("MuRIL Trainer created successfully!")

# Step 49: Train MuRIL

print("Starting MuRIL training...\n")

muril_train_result = muril_trainer.train()

print("\nMuRIL training completed successfully!")

# Step 50: Evaluate MuRIL on Test Dataset

print("Evaluating MuRIL on test dataset...\n")

muril_test_results = muril_trainer.evaluate(
    muril_test_tokenized
)

print("===== MuRIL Test Results =====")

for key, value in muril_test_results.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.4f}")

# Step 51: MuRIL Classification Report and Confusion Matrix

print("Generating MuRIL predictions...\n")

muril_predictions = muril_trainer.predict(
    muril_test_tokenized
)

muril_y_pred = np.argmax(
    muril_predictions.predictions,
    axis=1
)

muril_y_true = muril_predictions.label_ids

target_names = [
    "Negative",
    "Neutral",
    "Positive"
]

print("===== MuRIL Classification Report =====")

print(
    classification_report(
        muril_y_true,
        muril_y_pred,
        target_names=target_names,
        digits=4
    )
)

print("===== MuRIL Confusion Matrix =====")

muril_cm = confusion_matrix(
    muril_y_true,
    muril_y_pred
)

print(muril_cm)

# Step 52: Save MuRIL and Append Results

MURIL_SAVE_PATH = "./muril_sentiment_model"

# Save model and tokenizer
muril_trainer.save_model(MURIL_SAVE_PATH)
muril_tokenizer.save_pretrained(MURIL_SAVE_PATH)

print("MuRIL model saved successfully!")
print("Location:", MURIL_SAVE_PATH)


# Append MuRIL test results to the existing table
muril_result_row = pd.DataFrame([{
    "Model": "MuRIL",
    "Accuracy": muril_test_results["eval_accuracy"],
    "Precision": muril_test_results["eval_precision"],
    "Recall": muril_test_results["eval_recall"],
    "F1-Score": muril_test_results["eval_f1"]
}])

transformer_results = pd.concat(
    [transformer_results, muril_result_row],
    ignore_index=True
)

print("\n===== Transformer Results =====")

display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

# Step 53: Load DistilBERT Tokenizer and Model

DISTILBERT_MODEL_NAME = "distilbert-base-multilingual-cased"

distilbert_tokenizer = AutoTokenizer.from_pretrained(
    DISTILBERT_MODEL_NAME
)

distilbert_model = AutoModelForSequenceClassification.from_pretrained(
    DISTILBERT_MODEL_NAME,
    num_labels=NUM_LABELS,
    id2label={
        0: "Negative",
        1: "Neutral",
        2: "Positive"
    },
    label2id=label_mapping
)

print("DistilBERT loaded successfully!")
print("Model:", DISTILBERT_MODEL_NAME)
print("Number of labels:", NUM_LABELS)

# Step 54: Tokenize DistilBERT Datasets

def distilbert_tokenize_function(examples):
    return distilbert_tokenizer(
        examples["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

distilbert_train_tokenized = train_dataset.map(
    distilbert_tokenize_function,
    batched=True
)

distilbert_val_tokenized = val_dataset.map(
    distilbert_tokenize_function,
    batched=True
)

distilbert_test_tokenized = test_dataset.map(
    distilbert_tokenize_function,
    batched=True
)

print("DistilBERT tokenization completed!")

print("\nTrain features:")
print(distilbert_train_tokenized.features)

print("\nValidation features:")
print(distilbert_val_tokenized.features)

print("\nTest features:")
print(distilbert_test_tokenized.features)

# Step 55: Prepare DistilBERT Datasets for Training

distilbert_train_tokenized = distilbert_train_tokenized.remove_columns(["text"])
distilbert_val_tokenized = distilbert_val_tokenized.remove_columns(["text"])
distilbert_test_tokenized = distilbert_test_tokenized.remove_columns(["text"])

distilbert_train_tokenized.set_format("torch")
distilbert_val_tokenized.set_format("torch")
distilbert_test_tokenized.set_format("torch")

print("DistilBERT datasets prepared successfully!")

print("\nTrain columns:", distilbert_train_tokenized.column_names)
print("Validation columns:", distilbert_val_tokenized.column_names)
print("Test columns:", distilbert_test_tokenized.column_names)

# Step 56: DistilBERT Training Configuration

distilbert_training_args = TrainingArguments(
    output_dir="./distilbert_training_output",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    learning_rate=2e-5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    logging_strategy="epoch",
    report_to="none"
)

print("DistilBERT training configuration created successfully!")
print("Epochs:", distilbert_training_args.num_train_epochs)
print("Train batch size:", distilbert_training_args.per_device_train_batch_size)
print("Learning rate:", distilbert_training_args.learning_rate)

# Step 57: Create DistilBERT Trainer

distilbert_trainer = Trainer(
    model=distilbert_model,
    args=distilbert_training_args,
    train_dataset=distilbert_train_tokenized,
    eval_dataset=distilbert_val_tokenized,
    processing_class=distilbert_tokenizer,
    compute_metrics=compute_metrics
)

print("DistilBERT Trainer created successfully!")

# Step 58: Train DistilBERT

print("Starting DistilBERT training...\n")

distilbert_train_result = distilbert_trainer.train()

print("\nDistilBERT training completed successfully!")

# Step 59: Evaluate DistilBERT on Test Dataset

print("Evaluating DistilBERT on test dataset...\n")

distilbert_test_results = distilbert_trainer.evaluate(
    distilbert_test_tokenized
)

print("===== DistilBERT Test Results =====")

for key, value in distilbert_test_results.items():
    if isinstance(value, (int, float)):
        print(f"{key}: {value:.4f}")

# Step 60: DistilBERT Classification Report and Confusion Matrix

print("Generating DistilBERT predictions...\n")

distilbert_predictions = distilbert_trainer.predict(
    distilbert_test_tokenized
)

distilbert_y_pred = np.argmax(
    distilbert_predictions.predictions,
    axis=1
)

distilbert_y_true = distilbert_predictions.label_ids

target_names = [
    "Negative",
    "Neutral",
    "Positive"
]

print("===== DistilBERT Classification Report =====")

print(
    classification_report(
        distilbert_y_true,
        distilbert_y_pred,
        target_names=target_names,
        digits=4
    )
)

print("===== DistilBERT Confusion Matrix =====")

distilbert_cm = confusion_matrix(
    distilbert_y_true,
    distilbert_y_pred
)

print(distilbert_cm)

# Step 61: Save DistilBERT and Append Results

DISTILBERT_SAVE_PATH = "./distilbert_sentiment_model"

# Save model and tokenizer
distilbert_trainer.save_model(DISTILBERT_SAVE_PATH)
distilbert_tokenizer.save_pretrained(DISTILBERT_SAVE_PATH)

print("DistilBERT model saved successfully!")
print("Location:", DISTILBERT_SAVE_PATH)


# Append actual test results to the existing Transformer table
distilbert_result_row = pd.DataFrame([{
    "Model": "DistilBERT",
    "Accuracy": distilbert_test_results["eval_accuracy"],
    "Precision": distilbert_test_results["eval_precision"],
    "Recall": distilbert_test_results["eval_recall"],
    "F1-Score": distilbert_test_results["eval_f1"]
}])

transformer_results = pd.concat(
    [transformer_results, distilbert_result_row],
    ignore_index=True
)

print("\n===== Transformer Results =====")

display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

# Step 62: Final Transformer Comparison

transformer_results = transformer_results.sort_values(
    by="F1-Score",
    ascending=False
).reset_index(drop=True)

print("===== FINAL TRANSFORMER COMPARISON =====")

display(
    transformer_results.style.format({
        "Accuracy": "{:.4f}",
        "Precision": "{:.4f}",
        "Recall": "{:.4f}",
        "F1-Score": "{:.4f}"
    })
)

print("\nBest Transformer:")
print(transformer_results.iloc[0])

# Step 63: Save Transformer Results and Generate Graphs

import os
import matplotlib.pyplot as plt

# Create output folder
os.makedirs("./transformer_results", exist_ok=True)

# --------------------------------------------------
# 1. Save Transformer results as CSV
# --------------------------------------------------

transformer_results.to_csv(
    "./transformer_results/transformer_comparison.csv",
    index=False
)

print("Transformer comparison CSV saved!")


# --------------------------------------------------
# 2. Accuracy Comparison
# --------------------------------------------------

plt.figure(figsize=(10, 6))

plt.bar(
    transformer_results["Model"],
    transformer_results["Accuracy"]
)

plt.xlabel("Transformer Model")
plt.ylabel("Accuracy")
plt.title("Transformer Model Accuracy Comparison")
plt.ylim(0, 1)

plt.xticks(rotation=30, ha="right")
plt.tight_layout()

plt.savefig(
    "./transformer_results/transformer_accuracy_comparison.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# 3. F1-Score Comparison
# --------------------------------------------------

plt.figure(figsize=(10, 6))

plt.bar(
    transformer_results["Model"],
    transformer_results["F1-Score"]
)

plt.xlabel("Transformer Model")
plt.ylabel("F1-Score")
plt.title("Transformer Model F1-Score Comparison")
plt.ylim(0, 1)

plt.xticks(rotation=30, ha="right")
plt.tight_layout()

plt.savefig(
    "./transformer_results/transformer_f1_comparison.png",
    dpi=300
)

plt.show()


# --------------------------------------------------
# 4. Precision / Recall Comparison
# --------------------------------------------------

plt.figure(figsize=(10, 6))

x = range(len(transformer_results))

plt.plot(
    x,
    transformer_results["Precision"],
    marker="o",
    label="Precision"
)

plt.plot(
    x,
    transformer_results["Recall"],
    marker="o",
    label="Recall"
)

plt.xticks(
    x,
    transformer_results["Model"],
    rotation=30,
    ha="right"
)

plt.xlabel("Transformer Model")
plt.ylabel("Score")
plt.title("Transformer Precision and Recall Comparison")
plt.ylim(0, 1)

plt.legend()
plt.tight_layout()

plt.savefig(
    "./transformer_results/transformer_precision_recall_comparison.png",
    dpi=300
)

plt.show()


print("\n===== FILES CREATED =====")

for file in os.listdir("./transformer_results"):
    print(file)

# Step 64: Collect All Sentiment Transformer Files

import os
import shutil

BASE_DIR = "./sentiment_transformer_results"

os.makedirs(BASE_DIR, exist_ok=True)

# --------------------------------------------------
# 1. Copy Transformer comparison files
# --------------------------------------------------

if os.path.exists("./transformer_results"):
    shutil.copytree(
        "./transformer_results",
        os.path.join(BASE_DIR, "comparison"),
        dirs_exist_ok=True
    )

# --------------------------------------------------
# 2. Copy all trained Transformer models
# --------------------------------------------------

model_paths = {
    "BERT": "./bert_sentiment_model",
    "mBERT": "./mbert_sentiment_model",
    "RoBERTa": "./roberta_sentiment_model",
    "XLM-RoBERTa": "./xlmr_sentiment_model",
    "MuRIL": "./muril_sentiment_model",
    "DistilBERT": "./distilbert_sentiment_model"
}

for model_name, model_path in model_paths.items():

    if os.path.exists(model_path):

        destination = os.path.join(
            BASE_DIR,
            "models",
            model_name
        )

        shutil.copytree(
            model_path,
            destination,
            dirs_exist_ok=True
        )

        print(f"✅ {model_name} copied")

    else:
        print(f"⚠️ {model_name} folder not found: {model_path}")


# --------------------------------------------------
# 3. Display collected files
# --------------------------------------------------

print("\n===== SENTIMENT TRANSFORMER FILES =====")

for root, dirs, files_list in os.walk(BASE_DIR):

    level = root.replace(BASE_DIR, "").count(os.sep)
    indent = "    " * level

    print(f"{indent}{os.path.basename(root)}/")

    for file_name in files_list:
        print(f"{indent}    {file_name}")

# Step 65: Create Complete Sentiment Transformer ZIP

import shutil
import os

zip_path = shutil.make_archive(
    "./sentiment_transformer_complete",
    "zip",
    "./sentiment_transformer_results"
)

print("===== ZIP CREATED =====")
print("File:", zip_path)
print("Size:", round(os.path.getsize(zip_path) / (1024**2), 2), "MB")

from google.colab import files

files.download(
    "./sentiment_transformer_complete.zip"
)