# -*- coding: utf-8 -*-
"""sarcasm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVxuv8Aq6vOFGhnvgvortKPqrN7LG_QC

**Step 1 — Import Libraries + Load Sarcasm Dataset**
"""

# Step 1: Import required libraries

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

# Upload sarcasm dataset

from google.colab import files

uploaded = files.upload()

# Load the uploaded CSV file

import io

file_name = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("Dataset loaded successfully!")
print("File name:", file_name)

print("Dataset shape:", df.shape)

"""**Step 2 — View the dataset.**"""

# Step 2: View the dataset

print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

"""**Step 3 — Check column names.**"""

# Step 3: Check column names

print("Column names:")
print(df.columns.tolist())

# Step 4: Check data types

print(df.dtypes)

# Step 5: Check missing values

print(df.isnull().sum())

print("\nTotal missing values:",
      df.isnull().sum().sum())

# Step 6: Inspect the row with missing text

missing_text_rows = df[df['clean_tweet_v2'].isnull()]

display(missing_text_rows)

# Step 6: Remove rows with missing text

df = df.dropna(subset=['clean_tweet_v2']).copy()

print("Missing text rows removed.")
print("New dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

# Step 7: Check duplicate rows

duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

duplicate_percentage = (duplicate_rows / len(df)) * 100
print("Duplicate percentage:", duplicate_percentage, "%")

# Step 8: Check duplicate text

duplicate_text = df['clean_tweet_v2'].duplicated().sum()

print("Duplicate text entries:", duplicate_text)

if duplicate_text > 0:
    print("\nDuplicate texts found:")
    display(
        df[df['clean_tweet_v2'].duplicated(keep=False)]
        .sort_values('clean_tweet_v2')
    )
else:
    print("No duplicate texts found.")

# Step 9: Check duplicate text + label combinations

duplicate_text_label = df.duplicated(
    subset=['clean_tweet_v2', 'Label']
).sum()

print("Duplicate text + label combinations:",
      duplicate_text_label)

if duplicate_text_label > 0:
    print("\nDuplicate combinations found:")
    display(
        df[
            df.duplicated(
                subset=['clean_tweet_v2', 'Label'],
                keep=False
            )
        ].sort_values(['clean_tweet_v2', 'Label'])
    )
else:
    print("No duplicate text + label combinations found.")

# Step 10: Check sarcasm label distribution

label_counts = df['Label'].value_counts().sort_index()

print("Sarcasm label distribution:")
print(label_counts)

print("\nLabel percentages:")
label_percentages = df['Label'].value_counts(normalize=True).sort_index() * 100
print(label_percentages.round(2))

print("\nUnique labels:")
print(sorted(df['Label'].unique()))

# Step 11: Validate sarcasm labels

expected_labels = {-1, 1}
actual_labels = set(df['Label'].unique())

print("Expected labels:", expected_labels)
print("Actual labels:", actual_labels)

if actual_labels == expected_labels:
    print("\nAll sarcasm labels are valid!")
else:
    print("\nUnexpected labels found:")
    print(actual_labels - expected_labels)

# Step 12: Check empty or whitespace-only text

empty_text = (
    df['clean_tweet_v2']
    .astype(str)
    .str.strip()
    .eq('')
    .sum()
)

print("Empty or whitespace-only text:", empty_text)

empty_label = (
    df['Label']
    .astype(str)
    .str.strip()
    .eq('')
    .sum()
)

print("Empty labels:", empty_label)

# Step 13: Clean extra spaces in sarcasm text

df['clean_tweet_v2'] = df['clean_tweet_v2'].str.strip()
df['clean_tweet_v2'] = df['clean_tweet_v2'].str.replace(r'\s+', ' ', regex=True)

print("Sarcasm text cleaned successfully!")
print(df.head())

# Step 14: Check duplicate text after cleaning

duplicate_text_after_cleaning = df['clean_tweet_v2'].duplicated().sum()

print("Duplicate text after cleaning:", duplicate_text_after_cleaning)

if duplicate_text_after_cleaning > 0:
    print("\nDuplicate texts found:")
    display(
        df[df['clean_tweet_v2'].duplicated(keep=False)]
        .sort_values('clean_tweet_v2')
    )
else:
    print("No duplicate texts found after cleaning.")

# Step 15: Check text length and word count

df['text_length'] = df['clean_tweet_v2'].str.len()
df['word_count'] = df['clean_tweet_v2'].str.split().str.len()

print("Text length statistics:")
print(df['text_length'].describe())

print("\nWord count statistics:")
print(df['word_count'].describe())

print("\nShortest texts:")
display(
    df[['clean_tweet_v2', 'Label', 'text_length', 'word_count']]
    .sort_values('word_count')
    .head(10)
)

print("\nLongest texts:")
display(
    df[['clean_tweet_v2', 'Label', 'text_length', 'word_count']]
    .sort_values('word_count', ascending=False)
    .head(10)
)

# Step 16: Keep all columns for future use

print("Current columns:")
print(df.columns.tolist())

print("\nDataset shape:")
print(df.shape)

# Step 17: Final preprocessing validation

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nDuplicate texts:", df['clean_tweet_v2'].duplicated().sum())

print("\nSarcasm label distribution:")
print(df['Label'].value_counts().sort_index())

print("\nColumns:")
print(df.columns.tolist())

# Step 18: Create features (X) and target (y)

X = df['clean_tweet_v2']
y = df['Label']

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFirst 5 X values:")
print(X.head())

print("\nFirst 5 y values:")
print(y.head())

# Step 19: Encode sarcasm labels

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Label mapping:")

for label, encoded_value in zip(
    label_encoder.classes_,
    range(len(label_encoder.classes_))
):
    print(label, "→", encoded_value)

print("\nFirst 10 encoded labels:")
print(y_encoded[:10])

# Step 20: Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.20,
    random_state=42,
    stratify=y_encoded
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining label distribution:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nTesting label distribution:")
print(pd.Series(y_test).value_counts().sort_index())

# Step 21: Marathi-aware TF-IDF

import re
from sklearn.feature_extraction.text import TfidfVectorizer

def marathi_tokenizer(text):
    return re.findall(r'[\u0900-\u097F]+', text)

tfidf_vectorizer = TfidfVectorizer(
    tokenizer=marathi_tokenizer,
    token_pattern=None,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

# Step 22: Inspect TF-IDF vocabulary

feature_names = tfidf_vectorizer.get_feature_names_out()

print("Total TF-IDF features:", len(feature_names))

print("\nFirst 30 features:")
print(feature_names[:30])

# Check non-zero TF-IDF features

first_vector = X_train_tfidf[0]

print("\nNumber of non-zero features in first sentence:",
      first_vector.nnz)

print("TF-IDF vector shape:",
      first_vector.shape)

# Step 23: Train Logistic Regression

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

print("Logistic Regression model trained successfully!")

# Step 24: Logistic Regression predictions

y_pred_logistic = logistic_model.predict(X_test_tfidf)

print("Predictions generated successfully!")
print("Number of predictions:", len(y_pred_logistic))

print("\nFirst 10 predictions:")
print(y_pred_logistic[:10])

# Step 25: Evaluate Logistic Regression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

accuracy_logistic = accuracy_score(y_test, y_pred_logistic)

precision_logistic = precision_score(
    y_test,
    y_pred_logistic,
    average='weighted'
)

recall_logistic = recall_score(
    y_test,
    y_pred_logistic,
    average='weighted'
)

f1_logistic = f1_score(
    y_test,
    y_pred_logistic,
    average='weighted'
)

print("Logistic Regression Results")
print("---------------------------")
print("Accuracy :", round(accuracy_logistic, 4))
print("Precision:", round(precision_logistic, 4))
print("Recall   :", round(recall_logistic, 4))
print("F1-score :", round(f1_logistic, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_logistic,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_logistic))

# Step 26: Store Logistic Regression results

results = []

results.append({
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_logistic,
    'Precision': precision_logistic,
    'Recall': recall_logistic,
    'F1-Score': f1_logistic
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 27: Train Multinomial Naive Bayes

from sklearn.naive_bayes import MultinomialNB

naive_bayes_model = MultinomialNB()

naive_bayes_model.fit(X_train_tfidf, y_train)

print("Multinomial Naive Bayes model trained successfully!")

# Step 27: Train Multinomial Naive Bayes

from sklearn.naive_bayes import MultinomialNB

naive_bayes_model = MultinomialNB()

naive_bayes_model.fit(X_train_tfidf, y_train)

print("Multinomial Naive Bayes model trained successfully!")

# Step 28: Make Naive Bayes predictions

y_pred_nb = naive_bayes_model.predict(X_test_tfidf)

print("Predictions generated successfully!")
print("Number of predictions:", len(y_pred_nb))

print("\nFirst 10 predictions:")
print(y_pred_nb[:10])

# Step 29: Evaluate Multinomial Naive Bayes

accuracy_nb = accuracy_score(y_test, y_pred_nb)

precision_nb = precision_score(
    y_test,
    y_pred_nb,
    average='weighted'
)

recall_nb = recall_score(
    y_test,
    y_pred_nb,
    average='weighted'
)

f1_nb = f1_score(
    y_test,
    y_pred_nb,
    average='weighted'
)

print("Multinomial Naive Bayes Results")
print("--------------------------------")
print("Accuracy :", round(accuracy_nb, 4))
print("Precision:", round(precision_nb, 4))
print("Recall   :", round(recall_nb, 4))
print("F1-score :", round(f1_nb, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_nb,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_nb))

# Step 30: Store Naive Bayes results

results.append({
    'Model': 'Multinomial Naive Bayes',
    'Accuracy': accuracy_nb,
    'Precision': precision_nb,
    'Recall': recall_nb,
    'F1-Score': f1_nb
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 31: Train SVM

from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    random_state=42,
    max_iter=2000
)

svm_model.fit(X_train_tfidf, y_train)

print("SVM model trained successfully!")

# Step 32: SVM predictions

y_pred_svm = svm_model.predict(X_test_tfidf)

print("SVM predictions generated successfully!")
print("Number of predictions:", len(y_pred_svm))

print("\nFirst 10 predictions:")
print(y_pred_svm[:10])

# Step 33: Evaluate SVM

accuracy_svm = accuracy_score(y_test, y_pred_svm)

precision_svm = precision_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

recall_svm = recall_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

f1_svm = f1_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

print("SVM Results")
print("-----------")
print("Accuracy :", round(accuracy_svm, 4))
print("Precision:", round(precision_svm, 4))
print("Recall   :", round(recall_svm, 4))
print("F1-score :", round(f1_svm, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_svm,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

# Step 33: Evaluate SVM

accuracy_svm = accuracy_score(y_test, y_pred_svm)

precision_svm = precision_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

recall_svm = recall_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

f1_svm = f1_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

print("SVM Results")
print("-----------")
print("Accuracy :", round(accuracy_svm, 4))
print("Precision:", round(precision_svm, 4))
print("Recall   :", round(recall_svm, 4))
print("F1-score :", round(f1_svm, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_svm,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

# Step 34: Store SVM results

results.append({
    'Model': 'SVM',
    'Accuracy': accuracy_svm,
    'Precision': precision_svm,
    'Recall': recall_svm,
    'F1-Score': f1_svm
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 35: Train Random Forest

from sklearn.ensemble import RandomForestClassifier

random_forest_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

random_forest_model.fit(X_train_tfidf, y_train)

print("Random Forest model trained successfully!")

# Step 36: Random Forest predictions

y_pred_rf = random_forest_model.predict(X_test_tfidf)

print("Random Forest predictions generated successfully!")
print("Number of predictions:", len(y_pred_rf))

print("\nFirst 10 predictions:")
print(y_pred_rf[:10])

# Step 37: Evaluate Random Forest

accuracy_rf = accuracy_score(y_test, y_pred_rf)

precision_rf = precision_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

recall_rf = recall_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

f1_rf = f1_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

print("Random Forest Results")
print("---------------------")
print("Accuracy :", round(accuracy_rf, 4))
print("Precision:", round(precision_rf, 4))
print("Recall   :", round(recall_rf, 4))
print("F1-score :", round(f1_rf, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))

# Step 38: Store Random Forest results

results.append({
    'Model': 'Random Forest',
    'Accuracy': accuracy_rf,
    'Precision': precision_rf,
    'Recall': recall_rf,
    'F1-Score': f1_rf
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 39: Train Decision Tree

from sklearn.tree import DecisionTreeClassifier

decision_tree_model = DecisionTreeClassifier(
    random_state=42
)

decision_tree_model.fit(X_train_tfidf, y_train)

print("Decision Tree model trained successfully!")

# Step 40: Decision Tree predictions

y_pred_dt = decision_tree_model.predict(X_test_tfidf)

print("Decision Tree predictions generated successfully!")
print("Number of predictions:", len(y_pred_dt))

print("\nFirst 10 predictions:")
print(y_pred_dt[:10])

# Step 41: Evaluate Decision Tree

accuracy_dt = accuracy_score(y_test, y_pred_dt)

precision_dt = precision_score(
    y_test,
    y_pred_dt,
    average='weighted'
)

recall_dt = recall_score(
    y_test,
    y_pred_dt,
    average='weighted'
)

f1_dt = f1_score(
    y_test,
    y_pred_dt,
    average='weighted'
)

print("Decision Tree Results")
print("---------------------")
print("Accuracy :", round(accuracy_dt, 4))
print("Precision:", round(precision_dt, 4))
print("Recall   :", round(recall_dt, 4))
print("F1-score :", round(f1_dt, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_dt,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

# Step 42: Store Decision Tree results

results.append({
    'Model': 'Decision Tree',
    'Accuracy': accuracy_dt,
    'Precision': precision_dt,
    'Recall': recall_dt,
    'F1-Score': f1_dt
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 43: Final sarcasm model comparison

results_df = results_df.sort_values(
    by='F1-Score',
    ascending=False
).reset_index(drop=True)

display(results_df)

best_model_name = results_df.loc[0, 'Model']
best_accuracy = results_df.loc[0, 'Accuracy']
best_f1 = results_df.loc[0, 'F1-Score']

print("\nBest Sarcasm Model:", best_model_name)
print("Best Accuracy:", round(best_accuracy, 4))
print("Best F1-Score:", round(best_f1, 4))

# Step 44: Test the best sarcasm model on new Marathi sentences

best_sarcasm_model = logistic_model

new_sentences = [
    "वा! खूपच छान सेवा आहे, तीन तास वाट पाहायला लावली.",
    "आजचा कार्यक्रम खूप सुंदर आणि आनंददायी होता.",
    "काय अप्रतिम काम केलंस, सगळं बिघडवलंस.",
    "उद्या कॉलेजमध्ये परीक्षा होणार आहे.",
    "वा, किती सुंदर हवामान आहे, बाहेर पाऊसच पाऊस आहे."
]

# Convert new text using the SAME TF-IDF vectorizer
new_sentences_tfidf = tfidf_vectorizer.transform(new_sentences)

# Predict
new_predictions = best_sarcasm_model.predict(new_sentences_tfidf)

# Convert 0/1 back to original -1/1 labels
new_labels = label_encoder.inverse_transform(new_predictions)

print("New Sentence Predictions:\n")

for text, prediction in zip(new_sentences, new_labels):
    print("Text:", text)
    print("Prediction:", prediction)
    print("-" * 60)

# Step 45: Final validation of the best sarcasm model

best_sarcasm_model = logistic_model

y_pred_best_sarcasm = best_sarcasm_model.predict(X_test_tfidf)

final_accuracy_sarcasm = accuracy_score(
    y_test,
    y_pred_best_sarcasm
)

final_precision_sarcasm = precision_score(
    y_test,
    y_pred_best_sarcasm,
    average='weighted'
)

final_recall_sarcasm = recall_score(
    y_test,
    y_pred_best_sarcasm,
    average='weighted'
)

final_f1_sarcasm = f1_score(
    y_test,
    y_pred_best_sarcasm,
    average='weighted'
)

print("FINAL BEST MODEL: LOGISTIC REGRESSION")
print("--------------------------------------")
print("Accuracy :", round(final_accuracy_sarcasm, 4))
print("Precision:", round(final_precision_sarcasm, 4))
print("Recall   :", round(final_recall_sarcasm, 4))
print("F1-score :", round(final_f1_sarcasm, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_best_sarcasm,
        target_names=['Not Sarcastic', 'Sarcastic']
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_best_sarcasm
    )
)

# Step 46: Save the best sarcasm model and preprocessing components

import joblib

# Save best sarcasm model
joblib.dump(
    best_sarcasm_model,
    'sarcasm_logistic_regression.pkl'
)

# Save TF-IDF vectorizer
joblib.dump(
    tfidf_vectorizer,
    'sarcasm_tfidf_vectorizer.pkl'
)

# Save label encoder
joblib.dump(
    label_encoder,
    'sarcasm_label_encoder.pkl'
)

print("All sarcasm ML components saved successfully!")

import os

files_to_check = [
    'sarcasm_logistic_regression.pkl',
    'sarcasm_tfidf_vectorizer.pkl',
    'sarcasm_label_encoder.pkl'
]

print("Saved files:")

for file in files_to_check:
    print(file, "→", os.path.getsize(file), "bytes")

# Save final cleaned sarcasm dataset

final_sarcasm_dataset = df.copy()

final_sarcasm_dataset.to_csv(
    'final_sarcasm_dataset.csv',
    index=False,
    encoding='utf-8-sig'
)

print("Final sarcasm dataset saved successfully!")
print("Shape:", final_sarcasm_dataset.shape)
print("Columns:", final_sarcasm_dataset.columns.tolist())

from google.colab import files

files.download('sarcasm_logistic_regression.pkl')
files.download('sarcasm_tfidf_vectorizer.pkl')
files.download('sarcasm_label_encoder.pkl')

# Save final sarcasm dataset

final_sarcasm_dataset = df.copy()

final_sarcasm_dataset.to_csv(
    'final_sarcasm_dataset.csv',
    index=False,
    encoding='utf-8-sig'
)

print("Final sarcasm dataset saved successfully!")
print("Shape:", final_sarcasm_dataset.shape)
print("Columns:", final_sarcasm_dataset.columns.tolist())

from google.colab import files

files.download('final_sarcasm_dataset.csv')

import matplotlib.pyplot as plt
import numpy as np

# Sort by F1-score
results_df = results_df.sort_values(
    by='F1-Score',
    ascending=False
).reset_index(drop=True)

display(results_df)

plt.figure(figsize=(10, 6))

plt.bar(
    results_df['Model'],
    results_df['Accuracy'] * 100
)

plt.xlabel('ML Model')
plt.ylabel('Accuracy (%)')
plt.title('Marathi Sarcasm Detection - ML Model Accuracy Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(80, 95)

plt.tight_layout()

plt.savefig(
    'sarcasm_ml_accuracy_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

plt.figure(figsize=(10, 6))

plt.bar(
    results_df['Model'],
    results_df['F1-Score'] * 100
)

plt.xlabel('ML Model')
plt.ylabel('F1-Score (%)')
plt.title('Marathi Sarcasm Detection - ML Model F1-Score Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(80, 95)

plt.tight_layout()

plt.savefig(
    'sarcasm_ml_f1_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

metrics = [
    'Accuracy',
    'Precision',
    'Recall',
    'F1-Score'
]

x = np.arange(len(results_df['Model']))
width = 0.2

plt.figure(figsize=(12, 7))

plt.bar(
    x - 1.5 * width,
    results_df['Accuracy'] * 100,
    width,
    label='Accuracy'
)

plt.bar(
    x - 0.5 * width,
    results_df['Precision'] * 100,
    width,
    label='Precision'
)

plt.bar(
    x + 0.5 * width,
    results_df['Recall'] * 100,
    width,
    label='Recall'
)

plt.bar(
    x + 1.5 * width,
    results_df['F1-Score'] * 100,
    width,
    label='F1-Score'
)

plt.xlabel('ML Model')
plt.ylabel('Score (%)')
plt.title('Marathi Sarcasm Detection - ML Model Performance Comparison')

plt.xticks(
    x,
    results_df['Model'],
    rotation=45,
    ha='right'
)

plt.ylim(80, 95)
plt.legend()

plt.tight_layout()

plt.savefig(
    'sarcasm_ml_all_metrics_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

from google.colab import files

files.download('sarcasm_ml_accuracy_comparison.png')
files.download('sarcasm_ml_f1_comparison.png')
files.download('sarcasm_ml_all_metrics_comparison.png')

