# -*- coding: utf-8 -*-
"""sentiment_DL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s9-6MosjwNCe_LTWS3GuTWwXuxgI9RBo
"""

# Step 1: Import required libraries

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

# Upload final cleaned sentiment dataset

from google.colab import files

uploaded = files.upload()

# Load the dataset

import io

file_name = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("Dataset loaded successfully!")
print("File name:", file_name)
print("Dataset shape:", df.shape)

# Step 2: Validate the final sentiment dataset

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nDuplicate texts:", df['text'].duplicated().sum())

print("\nSentiment distribution:")
print(df['sentiment'].value_counts())

print("\nColumns:")
print(df.columns.tolist())

# Step 3: Prepare X and y for Deep Learning

X = df['text']
y = df['sentiment']

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFirst 5 text samples:")
print(X.head())

print("\nFirst 5 labels:")
print(y.head())

# Step 4: Encode sentiment labels

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Label mapping:")

for label, encoded_value in zip(
    label_encoder.classes_,
    range(len(label_encoder.classes_))
):
    print(label, "→", encoded_value)

print("\nFirst 10 encoded labels:")
print(y_encoded[:10])

# Step 5: Train, Validation, Test Split

from sklearn.model_selection import train_test_split

# First split: 80% train+validation, 20% test
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.20,
    random_state=42,
    stratify=y_encoded
)

# Second split: 90% training, 10% validation
X_train, X_val, y_train, y_val = train_test_split(
    X_train_val,
    y_train_val,
    test_size=0.10,
    random_state=42,
    stratify=y_train_val
)

print("Training samples:", len(X_train))
print("Validation samples:", len(X_val))
print("Testing samples:", len(X_test))

print("\nTraining distribution:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nValidation distribution:")
print(pd.Series(y_val).value_counts().sort_index())

print("\nTesting distribution:")
print(pd.Series(y_test).value_counts().sort_index())

# Step 6: Tokenization

from tensorflow.keras.preprocessing.text import Tokenizer

tokenizer = Tokenizer(
    num_words=10000,
    oov_token="<OOV>"
)

tokenizer.fit_on_texts(X_train)

X_train_seq = tokenizer.texts_to_sequences(X_train)
X_val_seq = tokenizer.texts_to_sequences(X_val)
X_test_seq = tokenizer.texts_to_sequences(X_test)

print("Tokenization completed successfully!")

print("\nVocabulary size:", len(tokenizer.word_index))

print("\nFirst training sequence:")
print(X_train_seq[0])

# Step 7: Analyze sequence lengths

train_lengths = [len(seq) for seq in X_train_seq]

print("Sequence length statistics:")
print(pd.Series(train_lengths).describe())

# Check useful percentiles

for percentile in [90, 95, 99, 100]:
    print(
        f"{percentile}th percentile:",
        int(np.percentile(train_lengths, percentile))
    )

# Step 8: Padding sequences

from tensorflow.keras.preprocessing.sequence import pad_sequences

MAX_LEN = 14

X_train_pad = pad_sequences(
    X_train_seq,
    maxlen=MAX_LEN,
    padding='post',
    truncating='post'
)

X_val_pad = pad_sequences(
    X_val_seq,
    maxlen=MAX_LEN,
    padding='post',
    truncating='post'
)

X_test_pad = pad_sequences(
    X_test_seq,
    maxlen=MAX_LEN,
    padding='post',
    truncating='post'
)

print("Training padded shape:", X_train_pad.shape)
print("Validation padded shape:", X_val_pad.shape)
print("Testing padded shape:", X_test_pad.shape)

print("\nFirst padded training sequence:")
print(X_train_pad[0])

# Step 9: One-hot encode labels

from tensorflow.keras.utils import to_categorical

y_train_cat = to_categorical(y_train, num_classes=3)
y_val_cat = to_categorical(y_val, num_classes=3)
y_test_cat = to_categorical(y_test, num_classes=3)

print("Training labels shape:", y_train_cat.shape)
print("Validation labels shape:", y_val_cat.shape)
print("Testing labels shape:", y_test_cat.shape)

print("\nFirst 5 training labels:")
print(y_train_cat[:5])

# Step 10: Common Deep Learning configuration

VOCAB_SIZE = 10000
MAX_LEN = 14
EMBEDDING_DIM = 128
NUM_CLASSES = 3

print("DL configuration:")
print("Vocabulary size :", VOCAB_SIZE)
print("Maximum length  :", MAX_LEN)
print("Embedding dim   :", EMBEDDING_DIM)
print("Number of classes:", NUM_CLASSES)

# Step 11: Build RNN model

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, SimpleRNN, Dense, Dropout

rnn_model = Sequential([
    Input(shape=(MAX_LEN,)),

    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),

    SimpleRNN(64),

    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(NUM_CLASSES, activation='softmax')
])

rnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

rnn_model.summary()

# Step 12: Train RNN

from tensorflow.keras.callbacks import EarlyStopping

early_stopping = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

rnn_history = rnn_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping],
    verbose=1
)

# Step 13: Evaluate RNN on test data

rnn_test_loss, rnn_test_accuracy = rnn_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("RNN Test Loss:", round(rnn_test_loss, 4))
print("RNN Test Accuracy:", round(rnn_test_accuracy, 4))

# RNN predictions

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

y_pred_rnn_prob = rnn_model.predict(X_test_pad, verbose=0)
y_pred_rnn = np.argmax(y_pred_rnn_prob, axis=1)

rnn_accuracy = accuracy_score(y_test, y_pred_rnn)
rnn_precision = precision_score(
    y_test, y_pred_rnn, average='weighted'
)
rnn_recall = recall_score(
    y_test, y_pred_rnn, average='weighted'
)
rnn_f1 = f1_score(
    y_test, y_pred_rnn, average='weighted'
)

print("\nRNN Results")
print("-----------")
print("Accuracy :", round(rnn_accuracy, 4))
print("Precision:", round(rnn_precision, 4))
print("Recall   :", round(rnn_recall, 4))
print("F1-score :", round(rnn_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rnn,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rnn))

# Step 14: Store RNN results

dl_results = []

dl_results.append({
    'Model': 'RNN',
    'Accuracy': rnn_accuracy,
    'Precision': rnn_precision,
    'Recall': rnn_recall,
    'F1-Score': rnn_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Step 15: Build LSTM model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Embedding, LSTM, Dense, Dropout

lstm_model = Sequential([
    Input(shape=(MAX_LEN,)),

    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),

    LSTM(64),

    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(NUM_CLASSES, activation='softmax')
])

lstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

lstm_model.summary()

# Step 16: Train LSTM

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_lstm = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

lstm_history = lstm_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_lstm],
    verbose=1
)

# Step 17: Evaluate LSTM on test data

lstm_test_loss, lstm_test_accuracy = lstm_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("LSTM Test Loss:", round(lstm_test_loss, 4))
print("LSTM Test Accuracy:", round(lstm_test_accuracy, 4))

# LSTM predictions and detailed metrics

y_pred_lstm_prob = lstm_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_lstm = np.argmax(
    y_pred_lstm_prob,
    axis=1
)

lstm_accuracy = accuracy_score(
    y_test,
    y_pred_lstm
)

lstm_precision = precision_score(
    y_test,
    y_pred_lstm,
    average='weighted'
)

lstm_recall = recall_score(
    y_test,
    y_pred_lstm,
    average='weighted'
)

lstm_f1 = f1_score(
    y_test,
    y_pred_lstm,
    average='weighted'
)

print("\nLSTM Results")
print("------------")
print("Accuracy :", round(lstm_accuracy, 4))
print("Precision:", round(lstm_precision, 4))
print("Recall   :", round(lstm_recall, 4))
print("F1-score :", round(lstm_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_lstm,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_lstm
    )
)

# Step 18: Store LSTM results

dl_results.append({
    'Model': 'LSTM',
    'Accuracy': lstm_accuracy,
    'Precision': lstm_precision,
    'Recall': lstm_recall,
    'F1-Score': lstm_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Step 19: Build BiLSTM model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    Embedding,
    LSTM,
    Bidirectional,
    Dense,
    Dropout
)

bilstm_model = Sequential([
    Input(shape=(MAX_LEN,)),

    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),

    Bidirectional(
        LSTM(64)
    ),

    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(NUM_CLASSES, activation='softmax')
])

bilstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

bilstm_model.summary()

# Step 20: Train BiLSTM

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_bilstm = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

bilstm_history = bilstm_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_bilstm],
    verbose=1
)

# Step 21: Evaluate BiLSTM on test data

bilstm_test_loss, bilstm_test_accuracy = bilstm_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("BiLSTM Test Loss:", round(bilstm_test_loss, 4))
print("BiLSTM Test Accuracy:", round(bilstm_test_accuracy, 4))

# BiLSTM predictions and detailed metrics

y_pred_bilstm_prob = bilstm_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_bilstm = np.argmax(
    y_pred_bilstm_prob,
    axis=1
)

bilstm_accuracy = accuracy_score(
    y_test,
    y_pred_bilstm
)

bilstm_precision = precision_score(
    y_test,
    y_pred_bilstm,
    average='weighted'
)

bilstm_recall = recall_score(
    y_test,
    y_pred_bilstm,
    average='weighted'
)

bilstm_f1 = f1_score(
    y_test,
    y_pred_bilstm,
    average='weighted'
)

print("\nBiLSTM Results")
print("--------------")
print("Accuracy :", round(bilstm_accuracy, 4))
print("Precision:", round(bilstm_precision, 4))
print("Recall   :", round(bilstm_recall, 4))
print("F1-score :", round(bilstm_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_bilstm,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_bilstm
    )
)

# Step 22: Store BiLSTM results

dl_results.append({
    'Model': 'BiLSTM',
    'Accuracy': bilstm_accuracy,
    'Precision': bilstm_precision,
    'Recall': bilstm_recall,
    'F1-Score': bilstm_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Step 23: Build CNN model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    Embedding,
    Conv1D,
    GlobalMaxPooling1D,
    Dense,
    Dropout
)

cnn_model = Sequential([
    Input(shape=(MAX_LEN,)),

    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),

    Conv1D(
        filters=128,
        kernel_size=3,
        activation='relu'
    ),

    GlobalMaxPooling1D(),

    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(NUM_CLASSES, activation='softmax')
])

cnn_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

cnn_model.summary()

# Step 24: Train CNN

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_cnn = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

cnn_history = cnn_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_cnn],
    verbose=1
)

# Step 25: Evaluate CNN on test data

cnn_test_loss, cnn_test_accuracy = cnn_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("CNN Test Loss:", round(cnn_test_loss, 4))
print("CNN Test Accuracy:", round(cnn_test_accuracy, 4))

# CNN predictions and detailed metrics

y_pred_cnn_prob = cnn_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_cnn = np.argmax(
    y_pred_cnn_prob,
    axis=1
)

cnn_accuracy = accuracy_score(
    y_test,
    y_pred_cnn
)

cnn_precision = precision_score(
    y_test,
    y_pred_cnn,
    average='weighted'
)

cnn_recall = recall_score(
    y_test,
    y_pred_cnn,
    average='weighted'
)

cnn_f1 = f1_score(
    y_test,
    y_pred_cnn,
    average='weighted'
)

print("\nCNN Results")
print("-----------")
print("Accuracy :", round(cnn_accuracy, 4))
print("Precision:", round(cnn_precision, 4))
print("Recall   :", round(cnn_recall, 4))
print("F1-score :", round(cnn_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_cnn,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_cnn
    )
)

# Step 26: Store CNN results

dl_results.append({
    'Model': 'CNN',
    'Accuracy': cnn_accuracy,
    'Precision': cnn_precision,
    'Recall': cnn_recall,
    'F1-Score': cnn_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Step 27: Build GRU model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    Embedding,
    GRU,
    Dense,
    Dropout
)

gru_model = Sequential([
    Input(shape=(MAX_LEN,)),

    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),

    GRU(64),

    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(NUM_CLASSES, activation='softmax')
])

gru_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

gru_model.summary()

# Step 28: Train GRU

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_gru = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

gru_history = gru_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_gru],
    verbose=1
)

# Step 29: Evaluate GRU on test data

gru_test_loss, gru_test_accuracy = gru_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("GRU Test Loss:", round(gru_test_loss, 4))
print("GRU Test Accuracy:", round(gru_test_accuracy, 4))

# GRU predictions and detailed metrics

y_pred_gru_prob = gru_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_gru = np.argmax(
    y_pred_gru_prob,
    axis=1
)

gru_accuracy = accuracy_score(
    y_test,
    y_pred_gru
)

gru_precision = precision_score(
    y_test,
    y_pred_gru,
    average='weighted'
)

gru_recall = recall_score(
    y_test,
    y_pred_gru,
    average='weighted'
)

gru_f1 = f1_score(
    y_test,
    y_pred_gru,
    average='weighted'
)

print("\nGRU Results")
print("-----------")
print("Accuracy :", round(gru_accuracy, 4))
print("Precision:", round(gru_precision, 4))
print("Recall   :", round(gru_recall, 4))
print("F1-score :", round(gru_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_gru,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_gru
    )
)

# Step 30: Store GRU results

dl_results.append({
    'Model': 'GRU',
    'Accuracy': gru_accuracy,
    'Precision': gru_precision,
    'Recall': gru_recall,
    'F1-Score': gru_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Step 31: Build CNN-BiLSTM model

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import (
    Input,
    Embedding,
    Conv1D,
    Bidirectional,
    LSTM,
    Dropout,
    Dense
)

cnn_bilstm_model = Sequential([
    Input(shape=(MAX_LEN,)),

    Embedding(
        input_dim=VOCAB_SIZE,
        output_dim=EMBEDDING_DIM
    ),

    Conv1D(
        filters=128,
        kernel_size=3,
        activation='relu'
    ),

    Bidirectional(
        LSTM(64)
    ),

    Dropout(0.3),

    Dense(32, activation='relu'),

    Dense(NUM_CLASSES, activation='softmax')
])

cnn_bilstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

cnn_bilstm_model.summary()

# Step 32: Train CNN-BiLSTM

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_cnn_bilstm = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

cnn_bilstm_history = cnn_bilstm_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_cnn_bilstm],
    verbose=1
)

# Step 33: Evaluate CNN-BiLSTM on test data

cnn_bilstm_test_loss, cnn_bilstm_test_accuracy = cnn_bilstm_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("CNN-BiLSTM Test Loss:", round(cnn_bilstm_test_loss, 4))
print("CNN-BiLSTM Test Accuracy:", round(cnn_bilstm_test_accuracy, 4))

# CNN-BiLSTM predictions and detailed metrics

y_pred_cnn_bilstm_prob = cnn_bilstm_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_cnn_bilstm = np.argmax(
    y_pred_cnn_bilstm_prob,
    axis=1
)

cnn_bilstm_accuracy = accuracy_score(
    y_test,
    y_pred_cnn_bilstm
)

cnn_bilstm_precision = precision_score(
    y_test,
    y_pred_cnn_bilstm,
    average='weighted'
)

cnn_bilstm_recall = recall_score(
    y_test,
    y_pred_cnn_bilstm,
    average='weighted'
)

cnn_bilstm_f1 = f1_score(
    y_test,
    y_pred_cnn_bilstm,
    average='weighted'
)

print("\nCNN-BiLSTM Results")
print("------------------")
print("Accuracy :", round(cnn_bilstm_accuracy, 4))
print("Precision:", round(cnn_bilstm_precision, 4))
print("Recall   :", round(cnn_bilstm_recall, 4))
print("F1-score :", round(cnn_bilstm_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_cnn_bilstm,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_cnn_bilstm
    )
)

# Step 34: Store CNN-BiLSTM results

dl_results.append({
    'Model': 'CNN-BiLSTM',
    'Accuracy': cnn_bilstm_accuracy,
    'Precision': cnn_bilstm_precision,
    'Recall': cnn_bilstm_recall,
    'F1-Score': cnn_bilstm_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Step 35: Build Attention-BiLSTM model

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input,
    Embedding,
    Bidirectional,
    LSTM,
    Attention,
    GlobalAveragePooling1D,
    Dense,
    Dropout
)

# Input
attention_input = Input(shape=(MAX_LEN,))

# Embedding
attention_embedding = Embedding(
    input_dim=VOCAB_SIZE,
    output_dim=EMBEDDING_DIM
)(attention_input)

# BiLSTM must return sequences for attention
attention_bilstm_output = Bidirectional(
    LSTM(64, return_sequences=True)
)(attention_embedding)

# Self-attention
attention_output = Attention()([
    attention_bilstm_output,
    attention_bilstm_output
])

# Pool the attended sequence
attention_pooled = GlobalAveragePooling1D()(attention_output)

# Classification layers
attention_dropout = Dropout(0.3)(attention_pooled)

attention_dense = Dense(
    32,
    activation='relu'
)(attention_dropout)

attention_output_final = Dense(
    NUM_CLASSES,
    activation='softmax'
)(attention_dense)

# Build model
attention_bilstm_model = Model(
    inputs=attention_input,
    outputs=attention_output_final
)

attention_bilstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

attention_bilstm_model.summary()

# Step 36: Train Attention-BiLSTM

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_attention = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

attention_bilstm_history = attention_bilstm_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_attention],
    verbose=1
)

# Step 37: Evaluate Attention-BiLSTM

attention_test_loss, attention_test_accuracy = attention_bilstm_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("Attention-BiLSTM Test Loss:", round(attention_test_loss, 4))
print("Attention-BiLSTM Test Accuracy:", round(attention_test_accuracy, 4))

# Attention-BiLSTM predictions and detailed metrics

y_pred_attention_prob = attention_bilstm_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_attention = np.argmax(
    y_pred_attention_prob,
    axis=1
)

attention_accuracy = accuracy_score(
    y_test,
    y_pred_attention
)

attention_precision = precision_score(
    y_test,
    y_pred_attention,
    average='weighted'
)

attention_recall = recall_score(
    y_test,
    y_pred_attention,
    average='weighted'
)

attention_f1 = f1_score(
    y_test,
    y_pred_attention,
    average='weighted'
)

print("\nAttention-BiLSTM Results")
print("------------------------")
print("Accuracy :", round(attention_accuracy, 4))
print("Precision:", round(attention_precision, 4))
print("Recall   :", round(attention_recall, 4))
print("F1-score :", round(attention_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_attention,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_attention
    )
)

# Step 38: Store Attention-BiLSTM results

dl_results.append({
    'Model': 'Attention-BiLSTM',
    'Accuracy': attention_accuracy,
    'Precision': attention_precision,
    'Recall': attention_recall,
    'F1-Score': attention_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(dl_results_df)

# Improved Parallel CNN + BiLSTM

from tensorflow.keras.models import Model
from tensorflow.keras.layers import (
    Input, Embedding, Conv1D, GlobalMaxPooling1D,
    Bidirectional, LSTM, Dense, Dropout, Concatenate
)

hybrid_input = Input(shape=(MAX_LEN,))

embedding = Embedding(
    input_dim=VOCAB_SIZE,
    output_dim=EMBEDDING_DIM
)(hybrid_input)

# CNN branch
cnn_branch = Conv1D(
    filters=128,
    kernel_size=3,
    activation='relu'
)(embedding)

cnn_branch = GlobalMaxPooling1D()(cnn_branch)

# BiLSTM branch
bilstm_branch = Bidirectional(
    LSTM(64)
)(embedding)

# Combine both representations
combined = Concatenate()([
    cnn_branch,
    bilstm_branch
])

combined = Dropout(0.3)(combined)

combined = Dense(
    64,
    activation='relu'
)(combined)

combined = Dropout(0.2)(combined)

output = Dense(
    NUM_CLASSES,
    activation='softmax'
)(combined)

hybrid_cnn_bilstm_model = Model(
    inputs=hybrid_input,
    outputs=output
)

hybrid_cnn_bilstm_model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

hybrid_cnn_bilstm_model.summary()

# Step 39: Train Parallel CNN + BiLSTM

from tensorflow.keras.callbacks import EarlyStopping

early_stopping_hybrid = EarlyStopping(
    monitor='val_loss',
    patience=3,
    restore_best_weights=True
)

hybrid_history = hybrid_cnn_bilstm_model.fit(
    X_train_pad,
    y_train_cat,
    validation_data=(X_val_pad, y_val_cat),
    epochs=15,
    batch_size=32,
    callbacks=[early_stopping_hybrid],
    verbose=1
)

# Step 40: Evaluate Parallel CNN + BiLSTM

hybrid_test_loss, hybrid_test_accuracy = hybrid_cnn_bilstm_model.evaluate(
    X_test_pad,
    y_test_cat,
    verbose=0
)

print("Hybrid Test Loss:", round(hybrid_test_loss, 4))
print("Hybrid Test Accuracy:", round(hybrid_test_accuracy, 4))

# Hybrid predictions and detailed metrics

y_pred_hybrid_prob = hybrid_cnn_bilstm_model.predict(
    X_test_pad,
    verbose=0
)

y_pred_hybrid = np.argmax(
    y_pred_hybrid_prob,
    axis=1
)

hybrid_accuracy = accuracy_score(
    y_test,
    y_pred_hybrid
)

hybrid_precision = precision_score(
    y_test,
    y_pred_hybrid,
    average='weighted'
)

hybrid_recall = recall_score(
    y_test,
    y_pred_hybrid,
    average='weighted'
)

hybrid_f1 = f1_score(
    y_test,
    y_pred_hybrid,
    average='weighted'
)

print("\nParallel CNN-BiLSTM Results")
print("---------------------------")
print("Accuracy :", round(hybrid_accuracy, 4))
print("Precision:", round(hybrid_precision, 4))
print("Recall   :", round(hybrid_recall, 4))
print("F1-score :", round(hybrid_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_hybrid,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(
    confusion_matrix(
        y_test,
        y_pred_hybrid
    )
)

# Step 41: Store Parallel CNN-BiLSTM results

dl_results.append({
    'Model': 'Parallel CNN-BiLSTM',
    'Accuracy': hybrid_accuracy,
    'Precision': hybrid_precision,
    'Recall': hybrid_recall,
    'F1-Score': hybrid_f1
})

dl_results_df = pd.DataFrame(dl_results)

display(
    dl_results_df.sort_values(
        by='F1-Score',
        ascending=False
    ).reset_index(drop=True)
)

# Step 42: Save Sentiment DL comparison

dl_results_df = dl_results_df.sort_values(
    by='F1-Score',
    ascending=False
).reset_index(drop=True)

dl_results_df.to_csv(
    'sentiment_dl_model_comparison.csv',
    index=False
)

print("Sentiment DL comparison saved successfully!")
display(dl_results_df)

# Step 41: Add Parallel CNN-BiLSTM result

dl_results.append({
    'Model': 'Parallel CNN-BiLSTM',
    'Accuracy': hybrid_accuracy,
    'Precision': hybrid_precision,
    'Recall': hybrid_recall,
    'F1-Score': hybrid_f1
})

dl_results_df = pd.DataFrame(dl_results)

# Sort by F1-score
dl_results_df = dl_results_df.sort_values(
    by='F1-Score',
    ascending=False
).reset_index(drop=True)

display(dl_results_df)

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))

plt.bar(
    dl_results_df['Model'],
    dl_results_df['Accuracy'] * 100
)

plt.xlabel('Deep Learning Model')
plt.ylabel('Accuracy (%)')
plt.title('Sentiment Analysis - DL Model Accuracy Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(85, 100)

plt.tight_layout()
plt.show()

plt.figure(figsize=(10, 6))

plt.bar(
    dl_results_df['Model'],
    dl_results_df['F1-Score'] * 100
)

plt.xlabel('Deep Learning Model')
plt.ylabel('F1-Score (%)')
plt.title('Sentiment Analysis - DL Model F1-Score Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(85, 100)

plt.tight_layout()
plt.show()

# Step 43: Save DL comparison results

dl_results_df.to_csv(
    'sentiment_dl_model_comparison.csv',
    index=False
)

print("Sentiment DL comparison saved successfully!")

# Save Accuracy graph

plt.figure(figsize=(10, 6))

plt.bar(
    dl_results_df['Model'],
    dl_results_df['Accuracy'] * 100
)

plt.xlabel('Deep Learning Model')
plt.ylabel('Accuracy (%)')
plt.title('Sentiment Analysis - DL Model Accuracy Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(85, 100)

plt.tight_layout()

plt.savefig(
    'sentiment_dl_accuracy_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# Save F1-score graph

plt.figure(figsize=(10, 6))

plt.bar(
    dl_results_df['Model'],
    dl_results_df['F1-Score'] * 100
)

plt.xlabel('Deep Learning Model')
plt.ylabel('F1-Score (%)')
plt.title('Sentiment Analysis - DL Model F1-Score Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(85, 100)

plt.tight_layout()

plt.savefig(
    'sentiment_dl_f1_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

# Step 45: Save best Sentiment DL model

import joblib

# Save CNN model
cnn_model.save('sentiment_cnn.keras')

# Save tokenizer
joblib.dump(
    tokenizer,
    'sentiment_dl_tokenizer.pkl'
)

# Save label encoder
joblib.dump(
    label_encoder,
    'sentiment_dl_label_encoder.pkl'
)

print("Best Sentiment DL model saved successfully!")

from google.colab import files

files_to_download = [
    'sentiment_dl_model_comparison.csv',
    'sentiment_dl_accuracy_comparison.png',
    'sentiment_dl_f1_comparison.png',
    'sentiment_cnn.keras',
    'sentiment_dl_tokenizer.pkl',
    'sentiment_dl_label_encoder.pkl'
]

for file in files_to_download:
    files.download(file)

