# -*- coding: utf-8 -*-
"""Sentiment Module.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KipnUieGTIHGep_spKrnHp6DZHSXZL_r
"""

# Step 1: Import Required Libraries

import pandas as pd
import numpy as np

print("Libraries imported successfully!")

# Step 2: Upload Dataset from Laptop

from google.colab import files

uploaded = files.upload()

# Load the uploaded CSV file

import io

file_name = list(uploaded.keys())[0]

df = pd.read_csv(io.BytesIO(uploaded[file_name]))

print("Dataset loaded successfully!")
print("File name:", file_name)

print(df.shape)

# Step 3: View the dataset

print("First 5 rows:")
display(df.head())

print("\nLast 5 rows:")
display(df.tail())

# Step 4: Check column names

print("Column names:")
print(df.columns.tolist())

# Step 5: Check data types

print(df.dtypes)

# Step 6: Check missing values

print(df.isnull().sum())

print("\nTotal missing values:", df.isnull().sum().sum())

# Step 7: Check duplicate rows

duplicate_rows = df.duplicated().sum()

print("Duplicate rows:", duplicate_rows)

duplicate_percentage = (duplicate_rows / len(df)) * 100

print("Duplicate percentage:", duplicate_percentage, "%")

# Step 8: Check duplicate text

duplicate_text = df['text'].duplicated().sum()

print("Duplicate text entries:", duplicate_text)

# Show duplicate texts if any

if duplicate_text > 0:
    display(df[df['text'].duplicated(keep=False)].sort_values('text'))
else:
    print("No duplicate texts found.")

# Step 9: Check duplicate text + sentiment combinations

duplicate_text_sentiment = df.duplicated(
    subset=['text', 'sentiment']
).sum()

print("Duplicate text + sentiment combinations:",
      duplicate_text_sentiment)

if duplicate_text_sentiment > 0:
    display(
        df[df.duplicated(
            subset=['text', 'sentiment'],
            keep=False
        )].sort_values(['text', 'sentiment'])
    )
else:
    print("No duplicate text + sentiment combinations found.")

# Step 10: Check sentiment distribution

sentiment_counts = df['sentiment'].value_counts()

print(sentiment_counts)

sentiment_percentage = df['sentiment'].value_counts(normalize=True) * 100

print("\nSentiment percentages:")
print(sentiment_percentage.round(2))

print("\nUnique sentiment labels:")
print(df['sentiment'].unique())

# Step 11: Validate sentiment labels

expected_labels = {'Positive', 'Negative', 'Neutral'}

actual_labels = set(df['sentiment'].unique())

print("Expected labels:", expected_labels)
print("Actual labels:", actual_labels)

if actual_labels == expected_labels:
    print("\nAll sentiment labels are valid!")
else:
    print("\nUnexpected sentiment labels found:")
    print(actual_labels - expected_labels)

# Step 12: Check domain distribution

domain_counts = df['domain'].value_counts()

print("Number of unique domains:", df['domain'].nunique())

print("\nDomain distribution:")
print(domain_counts)

domain_percentage = df['domain'].value_counts(normalize=True) * 100

print("\nDomain percentages:")
print(domain_percentage.round(2))

# Step 13: Check empty or whitespace-only text

empty_text = df['text'].astype(str).str.strip().eq('').sum()

print("Empty or whitespace-only text:", empty_text)

empty_sentiment = df['sentiment'].astype(str).str.strip().eq('').sum()
empty_domain = df['domain'].astype(str).str.strip().eq('').sum()

print("Empty sentiment:", empty_sentiment)
print("Empty domain:", empty_domain)

# Step 14: Clean extra spaces

df['text'] = df['text'].str.strip()
df['text'] = df['text'].str.replace(r'\s+', ' ', regex=True)

df['sentiment'] = df['sentiment'].str.strip()
df['domain'] = df['domain'].str.strip()

print("Text and categorical columns cleaned successfully!")

print(df.head())

# Step 15: Final duplicate check after text cleaning

duplicate_text_after_cleaning = df['text'].duplicated().sum()

print("Duplicate text after cleaning:",
      duplicate_text_after_cleaning)

if duplicate_text_after_cleaning > 0:
    print("\nDuplicate texts found after cleaning:")
    display(
        df[df['text'].duplicated(keep=False)]
        .sort_values('text')
    )
else:
    print("No duplicate texts found after cleaning.")

# Step 16: Check text length

df['text_length'] = df['text'].str.len()
df['word_count'] = df['text'].str.split().str.len()

print("Text length statistics:")
print(df['text_length'].describe())

print("\nWord count statistics:")
print(df['word_count'].describe())

print("\nShortest texts:")
display(df[['text', 'sentiment', 'text_length', 'word_count']]
        .sort_values('word_count')
        .head(10))

print("\nLongest texts:")
display(df[['text', 'sentiment', 'text_length', 'word_count']]
        .sort_values('word_count', ascending=False)
        .head(10))

# Step 17: Remove temporary analysis columns

df.drop(columns=['text_length', 'word_count'], inplace=True)

print("Temporary columns removed.")
print(df.columns.tolist())

# Step 18: Final preprocessing validation

print("Dataset shape:", df.shape)

print("\nMissing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

print("\nDuplicate texts:", df['text'].duplicated().sum())

print("\nSentiment distribution:")
print(df['sentiment'].value_counts())

print("\nColumns:")
print(df.columns.tolist())

"""**Phase 3 — Prepare Data for ML**"""

# Step 19: Create features (X) and target (y)

X = df['text']
y = df['sentiment']

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFirst 5 X values:")
print(X.head())

print("\nFirst 5 y values:")
print(y.head())

# Step 20: Encode sentiment labels

from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

y_encoded = label_encoder.fit_transform(y)

print("Label mapping:")
for label, encoded_value in zip(label_encoder.classes_, range(len(label_encoder.classes_))):
    print(label, "→", encoded_value)

print("\nFirst 10 encoded labels:")
print(y_encoded[:10])

# Step 21: Train-Test Split

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.20,
    random_state=42,
    stratify=y_encoded
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

print("\nTraining label distribution:")
print(pd.Series(y_train).value_counts().sort_index())

print("\nTesting label distribution:")
print(pd.Series(y_test).value_counts().sort_index())

# Corrected Step 22: Marathi-aware TF-IDF

import re
from sklearn.feature_extraction.text import TfidfVectorizer

def marathi_tokenizer(text):
    # Extract complete Devanagari words
    return re.findall(r'[\u0900-\u097F]+', text)

tfidf_vectorizer = TfidfVectorizer(
    tokenizer=marathi_tokenizer,
    token_pattern=None,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95
)

X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

print("Training TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

feature_names = tfidf_vectorizer.get_feature_names_out()

print("Total TF-IDF features:", len(feature_names))

print("\nFirst 30 features:")
print(feature_names[:30])

# Step 24: Logistic Regression

from sklearn.linear_model import LogisticRegression

logistic_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

logistic_model.fit(X_train_tfidf, y_train)

print("Logistic Regression model trained successfully!")

# Step 25: Make predictions using Logistic Regression

y_pred_logistic = logistic_model.predict(X_test_tfidf)

print("Predictions generated successfully!")
print("Number of predictions:", len(y_pred_logistic))

print("\nFirst 10 predictions:")
print(y_pred_logistic[:10])

# Step 26: Evaluate Logistic Regression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

accuracy_logistic = accuracy_score(y_test, y_pred_logistic)

precision_logistic = precision_score(
    y_test,
    y_pred_logistic,
    average='weighted'
)

recall_logistic = recall_score(
    y_test,
    y_pred_logistic,
    average='weighted'
)

f1_logistic = f1_score(
    y_test,
    y_pred_logistic,
    average='weighted'
)

print("Logistic Regression Results")
print("----------------------------")
print("Accuracy :", round(accuracy_logistic, 4))
print("Precision:", round(precision_logistic, 4))
print("Recall   :", round(recall_logistic, 4))
print("F1-score :", round(f1_logistic, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_logistic,
        target_names=label_encoder.classes_
    )
)

# Confusion Matrix

cm_logistic = confusion_matrix(y_test, y_pred_logistic)

print("Confusion Matrix:")
print(cm_logistic)

# Step 27: Store Logistic Regression results

results = []

results.append({
    'Model': 'Logistic Regression',
    'Accuracy': accuracy_logistic,
    'Precision': precision_logistic,
    'Recall': recall_logistic,
    'F1-Score': f1_logistic
})

print("Logistic Regression results stored successfully!")

results_df = pd.DataFrame(results)

display(results_df)

# Step 28: Train Multinomial Naive Bayes

from sklearn.naive_bayes import MultinomialNB

naive_bayes_model = MultinomialNB()

naive_bayes_model.fit(X_train_tfidf, y_train)

print("Multinomial Naive Bayes model trained successfully!")

# Step 29: Make predictions using Naive Bayes

y_pred_nb = naive_bayes_model.predict(X_test_tfidf)

print("Predictions generated successfully!")
print("Number of predictions:", len(y_pred_nb))

print("\nFirst 10 predictions:")
print(y_pred_nb[:10])

# Step 30: Evaluate Naive Bayes

accuracy_nb = accuracy_score(y_test, y_pred_nb)

precision_nb = precision_score(
    y_test,
    y_pred_nb,
    average='weighted'
)

recall_nb = recall_score(
    y_test,
    y_pred_nb,
    average='weighted'
)

f1_nb = f1_score(
    y_test,
    y_pred_nb,
    average='weighted'
)

print("Multinomial Naive Bayes Results")
print("--------------------------------")
print("Accuracy :", round(accuracy_nb, 4))
print("Precision:", round(precision_nb, 4))
print("Recall   :", round(recall_nb, 4))
print("F1-score :", round(f1_nb, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_nb,
        target_names=label_encoder.classes_
    )
)

# Confusion Matrix

cm_nb = confusion_matrix(y_test, y_pred_nb)

print("Confusion Matrix:")
print(cm_nb)

# Step 31: Store Naive Bayes results

results.append({
    'Model': 'Multinomial Naive Bayes',
    'Accuracy': accuracy_nb,
    'Precision': precision_nb,
    'Recall': recall_nb,
    'F1-Score': f1_nb
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 32: Train SVM

from sklearn.svm import LinearSVC

svm_model = LinearSVC(
    random_state=42,
    max_iter=2000
)

svm_model.fit(X_train_tfidf, y_train)

print("SVM model trained successfully!")

# Step 33: Make SVM predictions

y_pred_svm = svm_model.predict(X_test_tfidf)

print("SVM predictions generated successfully!")
print("Number of predictions:", len(y_pred_svm))

print("\nFirst 10 predictions:")
print(y_pred_svm[:10])

# Step 34: Evaluate SVM

accuracy_svm = accuracy_score(y_test, y_pred_svm)

precision_svm = precision_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

recall_svm = recall_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

f1_svm = f1_score(
    y_test,
    y_pred_svm,
    average='weighted'
)

print("SVM Results")
print("-----------")
print("Accuracy :", round(accuracy_svm, 4))
print("Precision:", round(precision_svm, 4))
print("Recall   :", round(recall_svm, 4))
print("F1-score :", round(f1_svm, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_svm,
        target_names=label_encoder.classes_
    )
)

# SVM Confusion Matrix

cm_svm = confusion_matrix(y_test, y_pred_svm)

print("Confusion Matrix:")
print(cm_svm)

# Step 35: Store SVM results

results.append({
    'Model': 'SVM',
    'Accuracy': accuracy_svm,
    'Precision': precision_svm,
    'Recall': recall_svm,
    'F1-Score': f1_svm
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 36: Train Random Forest

from sklearn.ensemble import RandomForestClassifier

random_forest_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    n_jobs=-1
)

random_forest_model.fit(X_train_tfidf, y_train)

print("Random Forest model trained successfully!")

# Step 37: Make Random Forest predictions

y_pred_rf = random_forest_model.predict(X_test_tfidf)

print("Random Forest predictions generated successfully!")
print("Number of predictions:", len(y_pred_rf))

print("\nFirst 10 predictions:")
print(y_pred_rf[:10])

# Step 38: Evaluate Random Forest

accuracy_rf = accuracy_score(y_test, y_pred_rf)

precision_rf = precision_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

recall_rf = recall_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

f1_rf = f1_score(
    y_test,
    y_pred_rf,
    average='weighted'
)

print("Random Forest Results")
print("---------------------")
print("Accuracy :", round(accuracy_rf, 4))
print("Precision:", round(precision_rf, 4))
print("Recall   :", round(recall_rf, 4))
print("F1-score :", round(f1_rf, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_rf,
        target_names=label_encoder.classes_
    )
)

# Random Forest Confusion Matrix

cm_rf = confusion_matrix(y_test, y_pred_rf)

print("Confusion Matrix:")
print(cm_rf)

# Step 39: Store Random Forest results

results.append({
    'Model': 'Random Forest',
    'Accuracy': accuracy_rf,
    'Precision': precision_rf,
    'Recall': recall_rf,
    'F1-Score': f1_rf
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 40: Train Decision Tree

from sklearn.tree import DecisionTreeClassifier

decision_tree_model = DecisionTreeClassifier(
    random_state=42
)

decision_tree_model.fit(X_train_tfidf, y_train)

print("Decision Tree model trained successfully!")

# Step 41: Make Decision Tree predictions

y_pred_dt = decision_tree_model.predict(X_test_tfidf)

print("Decision Tree predictions generated successfully!")
print("Number of predictions:", len(y_pred_dt))

print("\nFirst 10 predictions:")
print(y_pred_dt[:10])

# Step 42: Evaluate Decision Tree

accuracy_dt = accuracy_score(y_test, y_pred_dt)

precision_dt = precision_score(
    y_test,
    y_pred_dt,
    average='weighted'
)

recall_dt = recall_score(
    y_test,
    y_pred_dt,
    average='weighted'
)

f1_dt = f1_score(
    y_test,
    y_pred_dt,
    average='weighted'
)

print("Decision Tree Results")
print("---------------------")
print("Accuracy :", round(accuracy_dt, 4))
print("Precision:", round(precision_dt, 4))
print("Recall   :", round(recall_dt, 4))
print("F1-score :", round(f1_dt, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_dt,
        target_names=label_encoder.classes_
    )
)

# Decision Tree Confusion Matrix

cm_dt = confusion_matrix(y_test, y_pred_dt)

print("Confusion Matrix:")
print(cm_dt)

# Step 43: Store Decision Tree results

results.append({
    'Model': 'Decision Tree',
    'Accuracy': accuracy_dt,
    'Precision': precision_dt,
    'Recall': recall_dt,
    'F1-Score': f1_dt
})

results_df = pd.DataFrame(results)

display(results_df)

# Step 44: Final model comparison

results_df = results_df.sort_values(
    by='F1-Score',
    ascending=False
).reset_index(drop=True)

display(results_df)

# Best model

best_model_name = results_df.loc[0, 'Model']
best_f1_score = results_df.loc[0, 'F1-Score']
best_accuracy = results_df.loc[0, 'Accuracy']

print("Best Model:", best_model_name)
print("Best Accuracy:", round(best_accuracy, 4))
print("Best F1-Score:", round(best_f1_score, 4))

# Step 45: Test the best model on new Marathi sentences

new_sentences = [
    "आजचा दिवस खूप सुंदर आणि आनंददायी गेला.",
    "या सेवेचा अनुभव खूपच खराब होता.",
    "उद्या महाविद्यालयात नवीन वेळापत्रक लागू होईल.",
    "मला हे पुस्तक खूप आवडले.",
    "जेवणाची चव अजिबात चांगली नव्हती.",
    "बैठक उद्या सकाळी दहा वाजता होईल."
]

# Convert new sentences using the SAME TF-IDF vectorizer
new_sentences_tfidf = tfidf_vectorizer.transform(new_sentences)

# Predict using the BEST model
new_predictions = naive_bayes_model.predict(new_sentences_tfidf)

# Convert numerical predictions back to sentiment labels
new_labels = label_encoder.inverse_transform(new_predictions)

print("New Sentence Predictions:\n")

for sentence, prediction in zip(new_sentences, new_labels):
    print("Text:", sentence)
    print("Prediction:", prediction)
    print("-" * 60)

# Step 46: Final validation of the best model

best_model = naive_bayes_model

y_pred_best = best_model.predict(X_test_tfidf)

final_accuracy = accuracy_score(y_test, y_pred_best)
final_precision = precision_score(
    y_test,
    y_pred_best,
    average='weighted'
)
final_recall = recall_score(
    y_test,
    y_pred_best,
    average='weighted'
)
final_f1 = f1_score(
    y_test,
    y_pred_best,
    average='weighted'
)

print("FINAL BEST MODEL: MULTINOMIAL NAIVE BAYES")
print("-------------------------------------------")
print("Accuracy :", round(final_accuracy, 4))
print("Precision:", round(final_precision, 4))
print("Recall   :", round(final_recall, 4))
print("F1-score :", round(final_f1, 4))

print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_best,
        target_names=label_encoder.classes_
    )
)

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best))

# Step 47: Save the complete sentiment ML pipeline

import joblib

# Save the best model
joblib.dump(
    naive_bayes_model,
    'sentiment_naive_bayes.pkl'
)

# Save the TF-IDF vectorizer
joblib.dump(
    tfidf_vectorizer,
    'sentiment_tfidf_vectorizer.pkl'
)

# Save the label encoder
joblib.dump(
    label_encoder,
    'sentiment_label_encoder.pkl'
)

print("All sentiment ML components saved successfully!")

import os

files_to_check = [
    'sentiment_naive_bayes.pkl',
    'sentiment_tfidf_vectorizer.pkl',
    'sentiment_label_encoder.pkl'
]

print("Saved files:")

for file in files_to_check:
    print(file, "→", os.path.getsize(file), "bytes")

# Step 48: Load saved sentiment components

import joblib

loaded_model = joblib.load('sentiment_naive_bayes.pkl')
loaded_vectorizer = joblib.load('sentiment_tfidf_vectorizer.pkl')
loaded_label_encoder = joblib.load('sentiment_label_encoder.pkl')

print("All saved components loaded successfully!")

# Test loaded model

test_sentences = [
    "आजचा दिवस खूप सुंदर आहे.",
    "या सेवेचा अनुभव खूप खराब होता.",
    "उद्या महाविद्यालयात परीक्षा होईल."
]

test_tfidf = loaded_vectorizer.transform(test_sentences)

test_predictions = loaded_model.predict(test_tfidf)

test_labels = loaded_label_encoder.inverse_transform(test_predictions)

print("\nPredictions using saved model:\n")

for text, label in zip(test_sentences, test_labels):
    print("Text:", text)
    print("Prediction:", label)
    print("-" * 50)

from google.colab import files

files.download('sentiment_naive_bayes.pkl')

files.download('sentiment_tfidf_vectorizer.pkl')

files.download('sentiment_label_encoder.pkl')

# Create the final cleaned dataset

final_sentiment_dataset = df.copy()

final_sentiment_dataset.to_csv(
    'final_sentiment_dataset.csv',
    index=False,
    encoding='utf-8-sig'
)

print("Final dataset created successfully!")
print("Shape:", final_sentiment_dataset.shape)
print("Columns:", final_sentiment_dataset.columns.tolist())

from google.colab import files

files.download('final_sentiment_dataset.csv')

import matplotlib.pyplot as plt

# Make sure results are sorted by F1-score
results_df = results_df.sort_values(
    by='F1-Score',
    ascending=False
).reset_index(drop=True)

display(results_df)

plt.figure(figsize=(10, 6))

plt.bar(
    results_df['Model'],
    results_df['Accuracy'] * 100
)

plt.xlabel('ML Model')
plt.ylabel('Accuracy (%)')
plt.title('Marathi Sentiment Analysis - ML Model Accuracy Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(85, 100)

plt.tight_layout()

plt.savefig(
    'sentiment_ml_accuracy_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

plt.figure(figsize=(10, 6))

plt.bar(
    results_df['Model'],
    results_df['F1-Score'] * 100
)

plt.xlabel('ML Model')
plt.ylabel('F1-Score (%)')
plt.title('Marathi Sentiment Analysis - ML Model F1-Score Comparison')

plt.xticks(rotation=45, ha='right')
plt.ylim(85, 100)

plt.tight_layout()

plt.savefig(
    'sentiment_ml_f1_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

metrics = [
    'Accuracy',
    'Precision',
    'Recall',
    'F1-Score'
]

x = np.arange(len(results_df['Model']))
width = 0.2

plt.figure(figsize=(12, 7))

plt.bar(
    x - 1.5 * width,
    results_df['Accuracy'] * 100,
    width,
    label='Accuracy'
)

plt.bar(
    x - 0.5 * width,
    results_df['Precision'] * 100,
    width,
    label='Precision'
)

plt.bar(
    x + 0.5 * width,
    results_df['Recall'] * 100,
    width,
    label='Recall'
)

plt.bar(
    x + 1.5 * width,
    results_df['F1-Score'] * 100,
    width,
    label='F1-Score'
)

plt.xlabel('ML Model')
plt.ylabel('Score (%)')
plt.title('Marathi Sentiment Analysis - ML Model Performance Comparison')

plt.xticks(
    x,
    results_df['Model'],
    rotation=45,
    ha='right'
)

plt.ylim(85, 100)
plt.legend()

plt.tight_layout()

plt.savefig(
    'sentiment_ml_all_metrics_comparison.png',
    dpi=300,
    bbox_inches='tight'
)

plt.show()

from google.colab import files

files.download('sentiment_ml_accuracy_comparison.png')
files.download('sentiment_ml_f1_comparison.png')
files.download('sentiment_ml_all_metrics_comparison.png')

